Eigen: ParametrizedLine< _Scalar, _AmbientDim, Options > Class Template Reference
ParametrizedLine< _Scalar, _AmbientDim, Options > Class Template Reference
Geometry module
Detailed Description
template<typename _Scalar, int _AmbientDim, int Options = AutoAlign>
class Eigen::ParametrizedLine< _Scalar, _AmbientDim, Options >
A parametrized line.
This is defined in the Geometry module.
#include <Eigen/Geometry>
A parametrized line is defined by an origin point and a unit direction vector such that the line corresponds to the set , .
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
Public Member Functions
template<typename NewScalarType >
internal::cast_return_type
< ParametrizedLine,
ParametrizedLine
< NewScalarType,
AmbientDimAtCompileTime,
Options > >::type cast () const
Index dim () const
RealScalar distance (const VectorType &p) const
template<int OtherOptions>
_Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
_Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
ParametrizedLine< _Scalar,
_AmbientDim, _Options >
::VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
bool isApprox (const ParametrizedLine &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
ParametrizedLine ()
ParametrizedLine (Index _dim)
ParametrizedLine (const VectorType &origin, const VectorType &direction)
template<int OtherOptions>
ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane)
template<typename OtherScalarType , int OtherOptions>
ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
VectorType pointAt (const Scalar &t) const
VectorType projection (const VectorType &p) const
RealScalar squaredDistance (const VectorType &p) const
Static Public Member Functions
static ParametrizedLine Through (const VectorType &p0, const VectorType &p1)
Constructor & Destructor Documentation
ParametrizedLine () inline
Default constructor without initialization
Referenced by ParametrizedLine< _Scalar, _AmbientDim, Options >::cast(), and ParametrizedLine< _Scalar, _AmbientDim, Options >::Through().
ParametrizedLine (Index _dim) inline explicit
Constructs a dynamic-size line with _dim the dimension of the ambient space
ParametrizedLine (const VectorType & origin, const VectorType & direction) inline
Initializes a parametrized line of direction direction and origin origin.
Warning
the vector direction is assumed to be normalized.
ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) inline explicit
Constructs a parametrized line from a 2D hyperplane
Warning
the ambient space must have dimension 2 such that the hyperplane actually describes a line
References Hyperplane< _Scalar, _AmbientDim, Options >::normal(), and Hyperplane< _Scalar, _AmbientDim, Options >::offset().
ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
Member Function Documentation
internal::cast_return_type<ParametrizedLine, ParametrizedLine<NewScalarType,AmbientDimAtCompileTime,Options> >::type cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
References ParametrizedLine< _Scalar, _AmbientDim, Options >::ParametrizedLine().
Index dim () const inline
Returns
the dimension in which the line holds
RealScalar distance (const VectorType & p) const inline
Returns
the distance of a point p to its projection onto the line *this.
See Also
squaredDistance()
References ParametrizedLine< _Scalar, _AmbientDim, Options >::squaredDistance().
_Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Deprecated:
use intersectionParameter()
Returns
the parameter value of the intersection between *this and the given hyperplane
_Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the parameter value of the intersection between *this and the given hyperplane
References Hyperplane< _Scalar, _AmbientDim, Options >::normal(), and Hyperplane< _Scalar, _AmbientDim, Options >::offset().
ParametrizedLine<_Scalar, _AmbientDim,_Options>::VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the point of the intersection between *this and the given hyperplane
bool isApprox (const ParametrizedLine< _Scalar, _AmbientDim, Options > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType pointAt (const Scalar & t) const inline
Returns
the point at t along this line
VectorType projection (const VectorType & p) const inline
Returns
the projection of a point p onto the line *this.
RealScalar squaredDistance (const VectorType & p) const inline
Returns
the squared distance of a point p to its projection onto the line *this.
See Also
distance()
Referenced by ParametrizedLine< _Scalar, _AmbientDim, Options >::distance().
static ParametrizedLine Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a parametrized line going from p0 to p1.
References ParametrizedLine< _Scalar, _AmbientDim, Options >::ParametrizedLine().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
ParametrizedLine.h