Eigen: MatrixBase< Derived > Class Template Reference
MatrixBase< Derived > Class Template Reference
Core module
Detailed Description
template<typename Derived>
class Eigen::MatrixBase< Derived >
Base class for all dense matrices, vectors, and expressions.
This class is the base that is inherited by all matrix, vector, and related expression types. Most of the Eigen API is contained in this class, and its base classes. Other important classes for the Eigen API are Matrix, and VectorwiseOp.
Note that some methods are defined in other modules such as the LU module LU module for all functions related to matrix inversions.
Template Parameters
Derived is the derived type, e.g. a matrix type, or an expression, etc.
When writing a function taking Eigen objects as argument, if you want your function to take as argument any matrix, vector, or expression, just let it take a MatrixBase argument. As an example, here is a function printFirstRow which, given a matrix, vector, or expression x, prints the first row of x.
  template<typename Derived>
  void printFirstRow(const Eigen::MatrixBase<Derived>& x)
  {
    cout << x.row(0) << endl;
  }
*
This class can be extended with the help of the plugin mechanism described on the page Customizing/Extending Eigen by defining the preprocessor symbol EIGEN_MATRIXBASE_PLUGIN.
See Also
The class hierarchy
Public Types
enum {
RowsAtCompileTime,
ColsAtCompileTime,
SizeAtCompileTime,
MaxRowsAtCompileTime,
MaxColsAtCompileTime,
MaxSizeAtCompileTime,
IsVectorAtCompileTime,
Flags,
IsRowMajor ,
CoeffReadCost
}
typedef internal::traits
< Derived >::Index Index
The type of indices.
typedef Matrix< typename
internal::traits< Derived >
::Scalar, internal::traits
< Derived >::RowsAtCompileTime,
internal::traits< Derived >
::ColsAtCompileTime, AutoAlign|(internal::traits
< Derived >::Flags
&RowMajorBit?RowMajor:ColMajor),
internal::traits< Derived >
::MaxRowsAtCompileTime,
internal::traits< Derived >
::MaxColsAtCompileTime > PlainObject
The plain matrix type corresponding to this expression.
Public Member Functions
const AdjointReturnType adjoint () const
void adjointInPlace ()
bool all (void) const
bool allFinite () const
bool any (void) const
template<typename EssentialPart >
void applyHouseholderOnTheLeft (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
template<typename EssentialPart >
void applyHouseholderOnTheRight (const EssentialPart &essential, const Scalar &tau, Scalar *workspace)
template<typename OtherDerived >
void applyOnTheLeft (const EigenBase< OtherDerived > &other)
template<typename OtherScalar >
void applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > &j)
template<typename OtherDerived >
void applyOnTheRight (const EigenBase< OtherDerived > &other)
template<typename OtherScalar >
void applyOnTheRight (Index p, Index q, const JacobiRotation< OtherScalar > &j)
ArrayWrapper< Derived > array ()
const DiagonalWrapper< const
Derived > asDiagonal () const
template<typename CustomBinaryOp , typename OtherDerived >
const CwiseBinaryOp
< CustomBinaryOp, const
Derived, const OtherDerived > binaryExpr (const Eigen::MatrixBase< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
Block< Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const Block< const Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows,
BlockCols > block (Index startRow, Index startCol)
template<int BlockRows, int BlockCols>
const Block< const Derived,
BlockRows, BlockCols > block (Index startRow, Index startCol) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows,
BlockCols > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int BlockRows, int BlockCols>
const Block< const Derived,
BlockRows, BlockCols > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
RealScalar blueNorm () const
Block< Derived > bottomLeftCorner (Index cRows, Index cCols)
const Block< const Derived > bottomLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomLeftCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomLeftCorner (Index cRows, Index cCols) const
Block< Derived > bottomRightCorner (Index cRows, Index cCols)
const Block< const Derived > bottomRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomRightCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomRightCorner (Index cRows, Index cCols) const
RowsBlockXpr bottomRows (Index n)
ConstRowsBlockXpr bottomRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
template<typename NewType >
internal::cast_return_type
< Derived, const CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< Derived >::Scalar, NewType >
, const Derived > >::type cast () const
ColXpr col (Index i)
ConstColXpr col (Index i) const
const ColPivHouseholderQR
< PlainObject > colPivHouseholderQr () const
ConstColwiseReturnType colwise () const
ColwiseReturnType colwise ()
template<typename ResultType >
void computeInverseAndDetWithCheck (ResultType &inverse, typename ResultType::Scalar &determinant, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
template<typename ResultType >
void computeInverseWithCheck (ResultType &inverse, bool &invertible, const RealScalar &absDeterminantThreshold=NumTraits< Scalar >::dummy_precision()) const
ConjugateReturnType conjugate () const
Index count () const
template<typename OtherDerived >
MatrixBase< Derived >
::template
cross_product_return_type
< OtherDerived >::type cross (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
MatrixBase< Derived >::PlainObject cross3 (const MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const Derived > cwiseAbs () const
const CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const Derived > cwiseAbs2 () const
template<typename OtherDerived >
const CwiseBinaryOp
< std::equal_to< Scalar >
, const Derived, const
OtherDerived > cwiseEqual (const Eigen::MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< std::binder1st
< std::equal_to< Scalar >
>, const Derived > cwiseEqual (const Scalar &s) const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const Derived > cwiseInverse () const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const Derived,
const OtherDerived > cwiseMax (const Eigen::MatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const Derived,
const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const Derived,
const OtherDerived > cwiseMin (const Eigen::MatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const Derived,
const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const Derived, const
OtherDerived > cwiseNotEqual (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_product_op
< typename Derived::Scalar,
typename OtherDerived::Scalar >
, const Derived, const
OtherDerived > cwiseProduct (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const Derived,
const OtherDerived > cwiseQuotient (const Eigen::MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const Derived > cwiseSqrt () const
Scalar determinant () const
DiagonalReturnType diagonal ()
ConstDiagonalReturnType diagonal () const
DiagonalDynamicIndexReturnType diagonal (Index index)
ConstDiagonalDynamicIndexReturnType diagonal (Index index) const
Index diagonalSize () const
template<typename OtherDerived >
internal::scalar_product_traits
< typename internal::traits
< Derived >::Scalar, typename
internal::traits< OtherDerived >
::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > &other) const
EigenvaluesReturnType eigenvalues () const
Computes the eigenvalues of a matrix.
Matrix< Scalar, 3, 1 > eulerAngles (Index a0, Index a1, Index a2) const
EvalReturnType eval () const
void fill (const Scalar &value)
template<unsigned int Added, unsigned int Removed>
const Flagged< Derived, Added,
Removed > flagged () const
const ForceAlignedAccess< Derived > forceAlignedAccess () const
ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
internal::add_const_on_value_type
< typename
internal::conditional< Enable,
ForceAlignedAccess< Derived >
, Derived & >::type >::type forceAlignedAccessIf () const
template<bool Enable>
internal::conditional< Enable,
ForceAlignedAccess< Derived >
, Derived & >::type forceAlignedAccessIf ()
const WithFormat< Derived > format (const IOFormat &fmt) const
const FullPivHouseholderQR
< PlainObject > fullPivHouseholderQr () const
const FullPivLU< PlainObject > fullPivLu () const
bool hasNaN () const
SegmentReturnType head (Index n)
ConstSegmentReturnType head (Index n) const
template<int N>
FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
ConstFixedSegmentReturnType< N >
::Type head (Index n=N) const
const HNormalizedReturnType hnormalized () const
HomogeneousReturnType homogeneous () const
const HouseholderQR< PlainObject > householderQr () const
RealScalar hypotNorm () const
const ImagReturnType imag () const
NonConstImagReturnType imag ()
Index innerSize () const
const internal::inverse_impl
< Derived > inverse () const
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isDiagonal (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isIdentity (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isLowerTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isOrthogonal (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUnitary (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isUpperTriangular (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
JacobiSVD< PlainObject > jacobiSvd (unsigned int computationOptions=0) const
template<typename OtherDerived >
const LazyProductReturnType
< Derived, OtherDerived >
::Type lazyProduct (const MatrixBase< OtherDerived > &other) const
const LDLT< PlainObject > ldlt () const
ColsBlockXpr leftCols (Index n)
ConstColsBlockXpr leftCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
const LLT< PlainObject > llt () const
template<int p>
NumTraits< typename
internal::traits< Derived >
::Scalar >::Real lpNorm () const
const PartialPivLU< PlainObject > lu () const
template<typename EssentialPart >
void makeHouseholder (EssentialPart &essential, Scalar &tau, RealScalar &beta) const
void makeHouseholderInPlace (Scalar &tau, RealScalar &beta)
internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
Scalar mean () const
ColsBlockXpr middleCols (Index startCol, Index numCols)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
template<int N>
NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
RowsBlockXpr middleRows (Index startRow, Index n)
ConstRowsBlockXpr middleRows (Index startRow, Index n) const
template<int N>
NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
internal::traits< Derived >::Scalar minCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
const NestByValue< Derived > nestByValue () const
NoAlias< Derived,
Eigen::MatrixBase > noalias ()
Index nonZeros () const
RealScalar norm () const
void normalize ()
const PlainObject normalized () const
template<typename OtherDerived >
bool operator!= (const MatrixBase< OtherDerived > &other) const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const Derived > operator* (const std::complex< Scalar > &scalar) const
template<typename OtherDerived >
const ProductReturnType
< Derived, OtherDerived >
::Type operator* (const MatrixBase< OtherDerived > &other) const
template<typename DiagonalDerived >
const DiagonalProduct< Derived,
DiagonalDerived, OnTheRight > operator* (const DiagonalBase< DiagonalDerived > &diagonal) const
ScalarMultipleReturnType operator* (const UniformScaling< Scalar > &s) const
template<typename OtherDerived >
Derived & operator*= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_sum_op
< Scalar >, const Derived,
const OtherDerived > operator+ (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Derived & operator+= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_difference_op
< Scalar >, const Derived,
const OtherDerived > operator- (const Eigen::MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< Derived >::Scalar >, const
Derived > operator- () const
template<typename OtherDerived >
Derived & operator-= (const MatrixBase< OtherDerived > &other)
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< Derived >::Scalar >, const
Derived > operator/ (const Scalar &scalar) const
CommaInitializer< Derived > operator<< (const Scalar &s)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
Derived & operator= (const MatrixBase &other)
template<typename OtherDerived >
bool operator== (const MatrixBase< OtherDerived > &other) const
RealScalar operatorNorm () const
Computes the L2 operator norm.
Index outerSize () const
const PartialPivLU< PlainObject > partialPivLu () const
Scalar prod () const
RealReturnType real () const
NonConstRealReturnType real ()
template<typename Func >
internal::result_of< Func(typename
internal::traits< Derived >
::Scalar)>::type redux (const Func &func) const
template<int RowFactor, int ColFactor>
const Replicate< Derived,
RowFactor, ColFactor > replicate () const
const ReplicateReturnType replicate (Index rowFacor, Index colFactor) const
void resize (Index newSize)
void resize (Index nbRows, Index nbCols)
ReverseReturnType reverse ()
ConstReverseReturnType reverse () const
void reverseInPlace ()
ColsBlockXpr rightCols (Index n)
ConstColsBlockXpr rightCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
RowXpr row (Index i)
ConstRowXpr row (Index i) const
ConstRowwiseReturnType rowwise () const
RowwiseReturnType rowwise ()
SegmentReturnType segment (Index start, Index n)
ConstSegmentReturnType segment (Index start, Index n) const
template<int N>
FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
ConstFixedSegmentReturnType< N >
::Type segment (Index start, Index n=N) const
template<typename ThenDerived , typename ElseDerived >
const Select< Derived,
ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived,
ThenDerived, typename
ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived,
typename
ElseDerived::ConstantReturnType,
ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Derived & setConstant (const Scalar &value)
Derived & setIdentity ()
Derived & setIdentity (Index rows, Index cols)
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setOnes ()
Derived & setRandom ()
Derived & setZero ()
RealScalar squaredNorm () const
RealScalar stableNorm () const
Scalar sum () const
template<typename OtherDerived >
void swap (const DenseBase< OtherDerived > &other, int=OtherDerived::ThisConstantIsPrivateInPlainObjectBase)
template<typename OtherDerived >
void swap (PlainObjectBase< OtherDerived > &other)
SegmentReturnType tail (Index n)
ConstSegmentReturnType tail (Index n) const
template<int N>
FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
ConstFixedSegmentReturnType< N >
::Type tail (Index n=N) const
Block< Derived > topLeftCorner (Index cRows, Index cCols)
const Block< const Derived > topLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topLeftCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topLeftCorner (Index cRows, Index cCols) const
Block< Derived > topRightCorner (Index cRows, Index cCols)
const Block< const Derived > topRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topRightCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topRightCorner (Index cRows, Index cCols) const
RowsBlockXpr topRows (Index n)
ConstRowsBlockXpr topRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
Scalar trace () const
Eigen::Transpose< Derived > transpose ()
ConstTransposeReturnType transpose () const
void transposeInPlace ()
template<unsigned int Mode>
MatrixBase< Derived >
::template
TriangularViewReturnType< Mode >
::Type triangularView ()
template<unsigned int Mode>
MatrixBase< Derived >
::template
ConstTriangularViewReturnType
< Mode >::Type triangularView () const
template<typename CustomUnaryOp >
const CwiseUnaryOp
< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
const CwiseUnaryView
< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
PlainObject unitOrthogonal (void) const
CoeffReturnType value () const
template<typename Visitor >
void visit (Visitor &func) const
Static Public Member Functions
static const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static const ConstantReturnType Constant (Index size, const Scalar &value)
static const ConstantReturnType Constant (const Scalar &value)
static const IdentityReturnType Identity ()
static const IdentityReturnType Identity (Index rows, Index cols)
static const
SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
template<typename CustomNullaryOp >
static const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp &func)
static const ConstantReturnType Ones (Index rows, Index cols)
static const ConstantReturnType Ones (Index size)
static const ConstantReturnType Ones ()
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random (Index rows, Index cols)
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random (Index size)
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random ()
static const BasisReturnType Unit (Index size, Index i)
static const BasisReturnType Unit (Index i)
static const BasisReturnType UnitW ()
static const BasisReturnType UnitX ()
static const BasisReturnType UnitY ()
static const BasisReturnType UnitZ ()
static const ConstantReturnType Zero (Index rows, Index cols)
static const ConstantReturnType Zero (Index size)
static const ConstantReturnType Zero ()
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Member Typedef Documentation
typedef internal::traits<Derived>::Index Index inherited
The type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See Also
Preprocessor directives.
typedef Matrix<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags&RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime > PlainObject
The plain matrix type corresponding to this expression.
This is not necessarily exactly the return type of eval(). In the case of plain matrices, the return type of eval() is a const reference to a matrix, not a matrix! It is however guaranteed that the return type of eval() is either PlainObject or const PlainObject&.
Member Enumeration Documentation
anonymous enum inherited
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See Also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
Member Function Documentation
const MatrixBase< Derived >::AdjointReturnType adjoint () const inline
Returns
an expression of the adjoint (i.e. conjugate transpose) of *this.
Example:
Matrix2cf m = Matrix2cf::Random();
cout << "Here is the 2x2 complex matrix m:" << endl << m << endl;
cout << "Here is the adjoint of m:" << endl << m.adjoint() << endl;
Output:
Here is the 2x2 complex matrix m:
 (-0.211,0.68) (-0.605,0.823)
 (0.597,0.566)  (0.536,-0.33)
Here is the adjoint of m:
 (-0.211,-0.68)  (0.597,-0.566)
(-0.605,-0.823)    (0.536,0.33)
Warning
If you want to replace a matrix by its own adjoint, do NOT do this:
* m = m.adjoint(); // bug!!! caused by aliasing effect
*
Instead, use the adjointInPlace() method:
* m.adjointInPlace();
*
which gives Eigen good opportunities for optimization, or alternatively you can also do:
* m = m.adjoint().eval();
*
See Also
adjointInPlace(), transpose(), conjugate(), class Transpose, class internal::scalar_conjugate_op
void adjointInPlace () inline
This is the "in place" version of adjoint(): it replaces *this by its own transpose. Thus, doing
* m.adjointInPlace();
*
has the same effect on m as doing
* m = m.adjoint().eval();
*
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own adjoint. If you just need the adjoint of a matrix, use adjoint().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See Also
transpose(), adjoint(), transposeInPlace()
bool all (void) const inline inherited
Returns
true if all coefficients are true
Example:
Vector3f boxMin(Vector3f::Zero()), boxMax(Vector3f::Ones());
Vector3f p0 = Vector3f::Random(), p1 = Vector3f::Random().cwiseAbs();
// let's check if p0 and p1 are inside the axis aligned box defined by the corners boxMin,boxMax:
cout << "Is (" << p0.transpose() << ") inside the box: "
     << ((boxMin.array()<p0.array()).all() && (boxMax.array()>p0.array()).all()) << endl;
cout << "Is (" << p1.transpose() << ") inside the box: "
     << ((boxMin.array()<p1.array()).all() && (boxMax.array()>p1.array()).all()) << endl;
Output:
Is (0.68 -0.211  0.566) inside the box: 0
Is (0.597 0.823 0.605) inside the box: 1
See Also
any(), Cwise::operator<()
References Eigen::Dynamic.
bool allFinite () const inline inherited
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See Also
hasNaN()
bool any (void) const inline inherited
Returns
true if at least one coefficient is true
See Also
all()
References Eigen::Dynamic.
void applyHouseholderOnTheLeft (const EssentialPart & essential, const Scalar & tau, Scalar * workspace)
Apply the elementary reflector H given by with from the left to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() * essential.size() entries
See Also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheRight()
void applyHouseholderOnTheRight (const EssentialPart & essential, const Scalar & tau, Scalar * workspace)
Apply the elementary reflector H given by with from the right to a vector or matrix.
On input:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
workspace a pointer to working space with at least this->cols() * essential.size() entries
See Also
MatrixBase::makeHouseholder(), MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft()
void applyOnTheLeft (const EigenBase< OtherDerived > & other) inline
replaces *this by other * *this.
Example:
Matrix3f A = Matrix3f::Random(3,3), B;
B << 0,1,0,
     0,0,1,
     1,0,0;
cout << "At start, A = " << endl << A << endl;
A.applyOnTheLeft(B);
cout << "After applyOnTheLeft, A = " << endl << A << endl;
Output:
At start, A =
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
After applyOnTheLeft, A =
-0.211  0.823  0.536
 0.566 -0.605 -0.444
  0.68  0.597  -0.33
References EigenBase< Derived >::derived().
void applyOnTheLeft (Index p, Index q, const JacobiRotation< OtherScalar > & j) inline
This is defined in the Jacobi module.
#include <Eigen/Jacobi>
Applies the rotation in the plane j to the rows p and q of *this, i.e., it computes B = J * B, with .
See Also
class JacobiRotation, MatrixBase::applyOnTheRight(), internal::apply_rotation_in_the_plane()
void applyOnTheRight (const EigenBase< OtherDerived > & other) inline
replaces *this by *this * other. It is equivalent to MatrixBase::operator*=().
Example:
Matrix3f A = Matrix3f::Random(3,3), B;
B << 0,1,0,
     0,0,1,
     1,0,0;
cout << "At start, A = " << endl << A << endl;
A *= B;
cout << "After A *= B, A = " << endl << A << endl;
A.applyOnTheRight(B);  // equivalent to A *= B
cout << "After applyOnTheRight, A = " << endl << A << endl;
Output:
At start, A =
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
After A *= B, A =
 -0.33   0.68  0.597
 0.536 -0.211  0.823
-0.444  0.566 -0.605
After applyOnTheRight, A =
 0.597  -0.33   0.68
 0.823  0.536 -0.211
-0.605 -0.444  0.566
References EigenBase< Derived >::derived().
ArrayWrapper<Derived> array () inline
Returns
an Array expression of this matrix
See Also
ArrayBase::matrix()
const DiagonalWrapper< const Derived > asDiagonal () const inline
Returns
a pseudo-expression of a diagonal matrix with *this as vector of diagonal coefficients
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << Matrix3i(Vector3i(2,5,6).asDiagonal()) << endl;
Output:
2 0 0
0 5 0
0 0 6
See Also
class DiagonalWrapper, class DiagonalMatrix, diagonal(), isDiagonal()
Referenced by Transform< Scalar, Dim, Mode, _Options >::fromPositionOrientationScale(), Transform< Scalar, Dim, Mode, _Options >::prescale(), and Transform< Scalar, Dim, Mode, _Options >::scale().
const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> binaryExpr (const Eigen::MatrixBase< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template binary functor
template<typename Scalar> struct MakeComplexOp {
  EIGEN_EMPTY_STRUCT_CTOR(MakeComplexOp)
  typedef complex<Scalar> result_type;
  complex<Scalar> operator()(const Scalar& a, const Scalar& b) const { return complex<Scalar>(a,b); }
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random(), m2 = Matrix4d::Random();
  cout << m1.binaryExpr(m2, MakeComplexOp<double>()) << endl;
  return 0;
}
Output:
   (0.68,0.271)  (0.823,-0.967) (-0.444,-0.687)   (-0.27,0.998)
 (-0.211,0.435) (-0.605,-0.514)  (0.108,-0.198) (0.0268,-0.563)
 (0.566,-0.717)  (-0.33,-0.726) (-0.0452,-0.74)  (0.904,0.0259)
  (0.597,0.214)   (0.536,0.608)  (0.258,-0.782)   (0.832,0.678)
See Also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
Block<Derived> block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline inherited
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block(1, 1, 2, 2):" << endl << m.block(1, 1, 2, 2) << endl;
m.block(1, 1, 2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block(1, 1, 2, 2):
-6  1
-3  0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
const Block<const Derived> block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline inherited
This is the const version of block(Index,Index,Index,Index).
Block<Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) inline inherited
Returns
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block<2,2>(1,1):" << endl << m.block<2,2>(1,1) << endl;
m.block<2,2>(1,1).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block<2,2>(1,1):
-6  1
-3  0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) const inline inherited
This is the const version of block<>(Index, Index).
Block<Derived, BlockRows, BlockCols> block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline inherited
Returns
an expression of a block in *this.
Template Parameters
BlockRows number of rows in block as specified at compile-time
BlockCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal BlockRows unless BlockRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the block:" << endl << m.block<2, Dynamic>(1, 1, 2, 3) << endl;
m.block<2, Dynamic>(1, 1, 2, 3).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the block:" << endl << m.block<2, Dynamic>(1, 1, 2, 3) << endl;
m.block<2, Dynamic>(1, 1, 2, 3).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, BlockRows, BlockCols> block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline inherited
This is the const version of block<>(Index, Index, Index, Index).
NumTraits< typename internal::traits< Derived >::Scalar >::Real blueNorm () const inline
Returns
the l2 norm of *this using the Blue's algorithm. A Portable Fortran Program to Find the Euclidean Norm of a Vector, ACM TOMS, Vol 4, Issue 1, 1978.
For architecture/scalar types without vectorization, this version is much faster than stableNorm(). Otherwise the stableNorm() is faster.
See Also
norm(), stableNorm(), hypotNorm()
Block<Derived> bottomLeftCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner(2, 2):" << endl;
cout << m.bottomLeftCorner(2, 2) << endl;
m.bottomLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner(2, 2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> bottomLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomLeftCorner(Index, Index).
Block<Derived, CRows, CCols> bottomLeftCorner () inline inherited
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,2>():" << endl;
cout << m.bottomLeftCorner<2,2>() << endl;
m.bottomLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,2>():
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> bottomLeftCorner () const inline inherited
This is the const version of bottomLeftCorner<int, int>().
Block<Derived, CRows, CCols> bottomLeftCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,Dynamic>(2,2):" << endl;
cout << m.bottomLeftCorner<2,Dynamic>(2,2) << endl;
m.bottomLeftCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,Dynamic>(2,2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block
const Block<const Derived, CRows, CCols> bottomLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomLeftCorner<int, int>(Index, Index).
Block<Derived> bottomRightCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner(2, 2):" << endl;
cout << m.bottomRightCorner(2, 2) << endl;
m.bottomRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner(2, 2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> bottomRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomRightCorner(Index, Index).
Block<Derived, CRows, CCols> bottomRightCorner () inline inherited
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,2>():" << endl;
cout << m.bottomRightCorner<2,2>() << endl;
m.bottomRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,2>():
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> bottomRightCorner () const inline inherited
This is the const version of bottomRightCorner<int, int>().
Block<Derived, CRows, CCols> bottomRightCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,Dynamic>(2,2):" << endl;
cout << m.bottomRightCorner<2,Dynamic>(2,2) << endl;
m.bottomRightCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,Dynamic>(2,2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block
const Block<const Derived, CRows, CCols> bottomRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomRightCorner<int, int>(Index, Index).
RowsBlockXpr bottomRows (Index n) inline inherited
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows(2):" << endl;
cout << a.bottomRows(2) << endl;
a.bottomRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows(2):
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr bottomRows (Index n) const inline inherited
This is the const version of bottomRows(Index).
NRowsBlockXpr<N>::Type bottomRows (Index n = N) inline inherited
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows<2>():" << endl;
cout << a.bottomRows<2>() << endl;
a.bottomRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows<2>():
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type bottomRows (Index n = N) const inline inherited
This is the const version of bottomRows<int>().
internal::cast_return_type<Derived,const CwiseUnaryOp<internal::scalar_cast_op<typename internal::traits<Derived>::Scalar, NewType>, const Derived> >::type cast () const inline
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See Also
class CwiseUnaryOp
ColXpr col (Index i) inline inherited
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.col(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 4 0
0 5 0
0 6 1
See Also
row(), class Block
Referenced by VectorwiseOp< ExpressionType, Direction >::cross().
ConstColXpr col (Index i) const inline inherited
This is the const version of col().
const ColPivHouseholderQR< typename MatrixBase< Derived >::PlainObject > colPivHouseholderQr () const
Returns
the column-pivoting Householder QR decomposition of *this.
See Also
class ColPivHouseholderQR
const DenseBase< Derived >::ConstColwiseReturnType colwise () const inline inherited
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each column:" << endl << m.colwise().sum() << endl;
cout << "Here is the maximum absolute value of each column:"
     << endl << m.cwiseAbs().colwise().maxCoeff() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the sum of each column:
  1.04  0.815 -0.238
Here is the maximum absolute value of each column:
 0.68 0.823 0.536
See Also
rowwise(), class VectorwiseOp, Reductions, visitors and broadcasting
Referenced by Eigen::umeyama().
DenseBase< Derived >::ColwiseReturnType colwise () inline inherited
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See Also
rowwise(), class VectorwiseOp, Reductions, visitors and broadcasting
void computeInverseAndDetWithCheck (ResultType & inverse, typename ResultType::Scalar & determinant, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline
This is defined in the LU module.
#include <Eigen/LU>
Computation of matrix inverse and determinant, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Parameters
inverse Reference to the matrix in which to store the inverse.
determinant Reference to the variable in which to store the determinant.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
Matrix3d inverse;
bool invertible;
double determinant;
m.computeInverseAndDetWithCheck(inverse,determinant,invertible);
cout << "Its determinant is " << determinant << endl;
if(invertible) {
  cout << "It is invertible, and its inverse is:" << endl << inverse << endl;
}
else {
  cout << "It is not invertible." << endl;
}
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Its determinant is 0.209
It is invertible, and its inverse is:
-0.199   2.23   2.84
  1.01 -0.555  -1.42
 -1.62   3.59   3.29
See Also
inverse(), computeInverseWithCheck()
void computeInverseWithCheck (ResultType & inverse, bool & invertible, const RealScalar & absDeterminantThreshold = NumTraits<Scalar>::dummy_precision()) const inline
This is defined in the LU module.
#include <Eigen/LU>
Computation of matrix inverse, with invertibility check.
This is only for fixed-size square matrices of size up to 4x4.
Parameters
inverse Reference to the matrix in which to store the inverse.
invertible Reference to the bool variable in which to store whether the matrix is invertible.
absDeterminantThreshold Optional parameter controlling the invertibility check. The matrix will be declared invertible if the absolute value of its determinant is greater than this threshold.
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
Matrix3d inverse;
bool invertible;
m.computeInverseWithCheck(inverse,invertible);
if(invertible) {
  cout << "It is invertible, and its inverse is:" << endl << inverse << endl;
}
else {
  cout << "It is not invertible." << endl;
}
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
It is invertible, and its inverse is:
-0.199   2.23   2.84
  1.01 -0.555  -1.42
 -1.62   3.59   3.29
See Also
inverse(), computeInverseAndDetWithCheck()
ConjugateReturnType conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See Also
adjoint()
const DenseBase< Derived >::ConstantReturnType Constant (Index nbRows, Index nbCols, const Scalar & value) inline static inherited
Returns
an expression of a constant matrix of value value
The parameters nbRows and nbCols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass nbRows and nbCols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
const DenseBase< Derived >::ConstantReturnType Constant (Index size, const Scalar & value) inline static inherited
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
const DenseBase< Derived >::ConstantReturnType Constant (const Scalar & value) inline static inherited
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
DenseBase< Derived >::Index count () const inline inherited
Returns
the number of coefficients which evaluate to true
See Also
all(), any()
MatrixBase<Derived>::template cross_product_return_type<OtherDerived>::type cross (const MatrixBase< OtherDerived > & other) const inline
This is defined in the Geometry module.
#include <Eigen/Geometry>
Returns
the cross product of *this and other
Here is a very good explanation of cross-product: http://xkcd.com/199/
See Also
MatrixBase::cross3()
MatrixBase<Derived>::PlainObject cross3 (const MatrixBase< OtherDerived > & other) const inline
This is defined in the Geometry module.
#include <Eigen/Geometry>
Returns
the cross product of *this and other using only the x, y, and z coefficients
The size of *this and other must be four. This function is especially useful when using 4D vectors instead of 3D ones to get advantage of SSE/AltiVec vectorization.
See Also
MatrixBase::cross()
const CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> cwiseAbs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs() << endl;
Output:
2 4 6
5 1 0
See Also
cwiseAbs2()
const CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> cwiseAbs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs2() << endl;
Output:
 4 16 36
25  1  0
See Also
cwiseAbs()
const CwiseBinaryOp<std::equal_to<Scalar>, const Derived, const OtherDerived> cwiseEqual (const Eigen::MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are equal: " << count << endl;
Output:
Comparing m with identity matrix:
1 1
0 1
Number of coefficients that are equal: 3
See Also
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
const CwiseUnaryOp<std::binder1st<std::equal_to<Scalar> >, const Derived> cwiseEqual (const Scalar & s) const inline
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See Also
cwiseEqual(const MatrixBase<OtherDerived> &) const
Referenced by MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator==().
const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
MatrixXd m(2,3);
m << 2, 0.5, 1,
     3, 0.25, 1;
cout << m.cwiseInverse() << endl;
Output:
  0.5     2     1
0.333     4     1
See Also
cwiseProduct()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const Derived, const OtherDerived> cwiseMax (const Eigen::MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMax(w) << endl;
Output:
4
3
4
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const Derived, const ConstantReturnType> cwiseMax (const Scalar & other) const inline
Returns
an expression of the coefficient-wise max of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const Derived, const OtherDerived> cwiseMin (const Eigen::MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMin(w) << endl;
Output:
2
2
3
See Also
class CwiseBinaryOp, max()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const Derived, const ConstantReturnType> cwiseMin (const Scalar & other) const inline
Returns
an expression of the coefficient-wise min of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> cwiseNotEqual (const Eigen::MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseNotEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseNotEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are not equal: " << count << endl;
Output:
Comparing m with identity matrix:
0 0
1 0
Number of coefficients that are not equal: 1
See Also
cwiseEqual(), isApprox(), isMuchSmallerThan()
Referenced by MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator!=().
const CwiseBinaryOp<internal::scalar_product_op<typename Derived ::Scalar, typename OtherDerived ::Scalar >, const Derived , const OtherDerived > cwiseProduct (const Eigen::MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Matrix3i a = Matrix3i::Random(), b = Matrix3i::Random();
Matrix3i c = a.cwiseProduct(b);
cout << "a:\n" << a << "\nb:\n" << b << "\nc:\n" << c << endl;
Output:
a:
 7  6 -3
-2  9  6
 6 -6 -5
b:
 1 -3  9
 0  0  3
 3  9  5
c:
  7 -18 -27
  0   0  18
 18 -54 -25
See Also
class CwiseBinaryOp, cwiseAbs2
const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> cwiseQuotient (const Eigen::MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseQuotient(w) << endl;
Output:
 0.5
 1.5
1.33
See Also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
const CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Vector3d v(1,2,4);
cout << v.cwiseSqrt() << endl;
Output:
   1
1.41
   2
See Also
cwisePow(), cwiseSquare()
internal::traits< Derived >::Scalar determinant () const inline
This is defined in the LU module.
#include <Eigen/LU>
Returns
the determinant of this matrix
MatrixBase< Derived >::template DiagonalIndexReturnType< Index >::Type diagonal () inline
Returns
an expression of the main diagonal of the matrix *this
*this is not required to be square.
Example:
Matrix3i m = Matrix3i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here are the coefficients on the main diagonal of m:" << endl
     << m.diagonal() << endl;
Output:
Here is the matrix m:
 7  6 -3
-2  9  6
 6 -6 -5
Here are the coefficients on the main diagonal of m:
 7
 9
-5
See Also
class Diagonal
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here are the coefficients on the 1st super-diagonal and 2nd sub-diagonal of m:" << endl
     << m.diagonal<1>().transpose() << endl
     << m.diagonal<-2>().transpose() << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here are the coefficients on the 1st super-diagonal and 2nd sub-diagonal of m:
9 1 9
6 6
See Also
MatrixBase::diagonal(), class Diagonal
Referenced by AngleAxis< Scalar >::toRotationMatrix().
MatrixBase< Derived >::template ConstDiagonalIndexReturnType< Index >::Type diagonal () const inline
This is the const version of diagonal().
This is the const version of diagonal<int>().
MatrixBase< Derived >::DiagonalDynamicIndexReturnType diagonal (Index index) inline
Returns
an expression of the DiagIndex-th sub or super diagonal of the matrix *this
*this is not required to be square.
The template parameter DiagIndex represent a super diagonal if DiagIndex > 0 and a sub diagonal otherwise. DiagIndex == 0 is equivalent to the main diagonal.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here are the coefficients on the 1st super-diagonal and 2nd sub-diagonal of m:" << endl
     << m.diagonal(1).transpose() << endl
     << m.diagonal(-2).transpose() << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here are the coefficients on the 1st super-diagonal and 2nd sub-diagonal of m:
9 1 9
6 6
See Also
MatrixBase::diagonal(), class Diagonal
MatrixBase< Derived >::ConstDiagonalDynamicIndexReturnType diagonal (Index index) const inline
This is the const version of diagonal(Index).
Index diagonalSize () const inline
Returns
the size of the main diagonal, which is min(rows(),cols()).
See Also
rows(), cols(), SizeAtCompileTime.
internal::scalar_product_traits< typename internal::traits< Derived >::Scalar, typename internal::traits< OtherDerived >::Scalar >::ReturnType dot (const MatrixBase< OtherDerived > & other) const
Returns
the dot product of *this with other.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Note
If the scalar type is complex numbers, then this function returns the hermitian (sesquilinear) dot product, conjugate-linear in the first variable and linear in the second variable.
See Also
squaredNorm(), norm()
MatrixBase< Derived >::EigenvaluesReturnType eigenvalues () const inline
Computes the eigenvalues of a matrix.
Returns
Column vector containing the eigenvalues.
This is defined in the Eigenvalues module.
#include <Eigen/Eigenvalues>
This function computes the eigenvalues with the help of the EigenSolver class (for real matrices) or the ComplexEigenSolver class (for complex matrices).
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix.
The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
MatrixXd ones = MatrixXd::Ones(3,3);
VectorXcd eivals = ones.eigenvalues();
cout << "The eigenvalues of the 3x3 matrix of ones are:" << endl << eivals << endl;
Output:
The eigenvalues of the 3x3 matrix of ones are:
(-5.31e-17,0)
        (3,0)
        (0,0)
See Also
EigenSolver::eigenvalues(), ComplexEigenSolver::eigenvalues(), SelfAdjointView::eigenvalues()
EvalReturnType eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
void fill (const Scalar & val) inline inherited
Alias for setConstant(): sets all coefficients in this expression to val.
See Also
setConstant(), Constant(), class CwiseNullaryOp
Referenced by PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::determinant().
const Flagged< Derived, Added, Removed > flagged () const inline inherited
Returns
an expression of *this with added and removed flags
This is mostly for internal use.
See Also
class Flagged
const ForceAlignedAccess< Derived > forceAlignedAccess () const inline
Returns
an expression of *this with forced aligned access
See Also
forceAlignedAccessIf(),class ForceAlignedAccess
ForceAlignedAccess< Derived > forceAlignedAccess () inline
Returns
an expression of *this with forced aligned access
See Also
forceAlignedAccessIf(), class ForceAlignedAccess
internal::add_const_on_value_type< typename internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type >::type forceAlignedAccessIf () const inline
Returns
an expression of *this with forced aligned access if Enable is true.
See Also
forceAlignedAccess(), class ForceAlignedAccess
internal::conditional< Enable, ForceAlignedAccess< Derived >, Derived & >::type forceAlignedAccessIf () inline
Returns
an expression of *this with forced aligned access if Enable is true.
See Also
forceAlignedAccess(), class ForceAlignedAccess
const WithFormat< Derived > format (const IOFormat & fmt) const inline inherited
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See Also
class IOFormat, class WithFormat
const FullPivHouseholderQR< typename MatrixBase< Derived >::PlainObject > fullPivHouseholderQr () const
Returns
the full-pivoting Householder QR decomposition of *this.
See Also
class FullPivHouseholderQR
const FullPivLU< typename MatrixBase< Derived >::PlainObject > fullPivLu () const inline
This is defined in the LU module.
#include <Eigen/LU>
Returns
the full-pivoting LU decomposition of *this.
See Also
class FullPivLU
bool hasNaN () const inline inherited
Returns
true is *this contains at least one Not A Number (NaN).
See Also
allFinite()
SegmentReturnType head (Index n) inline inherited
Returns
a dynamic-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head(2) << endl;
v.head(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
ConstSegmentReturnType head (Index n) const inline inherited
This is the const version of head(Index).
FixedSegmentReturnType<N>::Type head (Index n = N) inline inherited
Returns
a fixed-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head<2>() << endl;
v.head<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
See Also
class Block
ConstFixedSegmentReturnType<N>::Type head (Index n = N) const inline inherited
This is the const version of head<int>().
const MatrixBase< Derived >::HNormalizedReturnType hnormalized () const inline
This is defined in the Geometry module.
#include <Eigen/Geometry>
Returns
an expression of the homogeneous normalized vector of *this
Example:
Output:
See Also
VectorwiseOp::hnormalized()
MatrixBase< Derived >::HomogeneousReturnType homogeneous () const inline
This is defined in the Geometry module.
#include <Eigen/Geometry>
Returns
an expression of the equivalent homogeneous vector
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
Output:
See Also
class Homogeneous
const HouseholderQR< typename MatrixBase< Derived >::PlainObject > householderQr () const
Returns
the Householder QR decomposition of *this.
See Also
class HouseholderQR
NumTraits< typename internal::traits< Derived >::Scalar >::Real hypotNorm () const inline
Returns
the l2 norm of *this avoiding undeflow and overflow. This version use a concatenation of hypot() calls, and it is very slow.
See Also
norm(), stableNorm()
const MatrixBase< Derived >::IdentityReturnType Identity () inline static
Returns
an expression of the identity matrix (not necessarily square).
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variant taking size arguments.
Example:
cout << Matrix<double, 3, 4>::Identity() << endl;
Output:
1 0 0 0
0 1 0 0
0 0 1 0
See Also
Identity(Index,Index), setIdentity(), isIdentity()
References DenseBase< Derived >::NullaryExpr().
const MatrixBase< Derived >::IdentityReturnType Identity (Index nbRows, Index nbCols) inline static
Returns
an expression of the identity matrix (not necessarily square).
The parameters nbRows and nbCols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Identity() should be used instead.
Example:
cout << MatrixXd::Identity(4, 3) << endl;
Output:
1 0 0
0 1 0
0 0 1
0 0 0
See Also
Identity(), setIdentity(), isIdentity()
References DenseBase< Derived >::NullaryExpr().
const ImagReturnType imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See Also
real()
NonConstImagReturnType imag () inline
Returns
a non const expression of the imaginary part of *this.
See Also
real()
Index innerSize () const inline inherited
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
const internal::inverse_impl< Derived > inverse () const inline
This is defined in the LU module.
#include <Eigen/LU>
Returns
the matrix inverse of this matrix.
For small fixed sizes up to 4x4, this method uses cofactors. In the general case, this method uses class PartialPivLU.
Note
This matrix must be invertible, otherwise the result is undefined. If you need an invertibility check, do the following:
for fixed sizes up to 4x4, use computeInverseAndDetWithCheck().
for the general case, use class FullPivLU.
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Its inverse is:" << endl << m.inverse() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Its inverse is:
-0.199   2.23   2.84
  1.01 -0.555  -1.42
 -1.62   3.59   3.29
See Also
computeInverseAndDetWithCheck()
Referenced by Hyperplane< _Scalar, _AmbientDim, Options >::transform().
bool isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See Also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
Referenced by Transform< Scalar, Dim, Mode, _Options >::isApprox().
bool isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
bool isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
bool isDiagonal (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a diagonal matrix, within the precision given by prec.
Example:
Matrix3d m = 10000 * Matrix3d::Identity();
m(0,2) = 1;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isDiagonal() returns: " << m.isDiagonal() << endl;
cout << "m.isDiagonal(1e-3) returns: " << m.isDiagonal(1e-3) << endl;
Output:
Here's the matrix m:
1e+04     0     1
    0 1e+04     0
    0     0 1e+04
m.isDiagonal() returns: 0
m.isDiagonal(1e-3) returns: 1
See Also
asDiagonal()
bool isIdentity (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the identity matrix (not necessarily square), within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Identity();
m(0,2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isIdentity() returns: " << m.isIdentity() << endl;
cout << "m.isIdentity(1e-3) returns: " << m.isIdentity(1e-3) << endl;
Output:
Here's the matrix m:
     1      0 0.0001
     0      1      0
     0      0      1
m.isIdentity() returns: 0
m.isIdentity(1e-3) returns: 1
See Also
class CwiseNullaryOp, Identity(), Identity(Index,Index), setIdentity()
bool isLowerTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to a lower triangular matrix, within the precision given by prec.
See Also
isUpperTriangular()
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const inherited
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See Also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
bool isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See Also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
bool isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Ones();
m(0,2) += 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isOnes() returns: " << m.isOnes() << endl;
cout << "m.isOnes(1e-3) returns: " << m.isOnes(1e-3) << endl;
Output:
Here's the matrix m:
1 1 1
1 1 1
1 1 1
m.isOnes() returns: 0
m.isOnes(1e-3) returns: 1
See Also
class CwiseNullaryOp, Ones()
bool isOrthogonal (const MatrixBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately orthogonal to other, within the precision given by prec.
Example:
Vector3d v(1,0,0);
Vector3d w(1e-4,0,1);
cout << "Here's the vector v:" << endl << v << endl;
cout << "Here's the vector w:" << endl << w << endl;
cout << "v.isOrthogonal(w) returns: " << v.isOrthogonal(w) << endl;
cout << "v.isOrthogonal(w,1e-3) returns: " << v.isOrthogonal(w,1e-3) << endl;
Output:
Here's the vector v:
1
0
0
Here's the vector w:
0.0001
     0
     1
v.isOrthogonal(w) returns: 0
v.isOrthogonal(w,1e-3) returns: 1
bool isUnitary (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately an unitary matrix, within the precision given by prec. In the case where the Scalar type is real numbers, a unitary matrix is an orthogonal matrix, whence the name.
Note
This can be used to check whether a family of vectors forms an orthonormal basis. Indeed, m.isUnitary() returns true if and only if the columns (equivalently, the rows) of m form an orthonormal basis.
Example:
Matrix3d m = Matrix3d::Identity();
m(0,2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isUnitary() returns: " << m.isUnitary() << endl;
cout << "m.isUnitary(1e-3) returns: " << m.isUnitary(1e-3) << endl;
Output:
Here's the matrix m:
     1      0 0.0001
     0      1      0
     0      0      1
m.isUnitary() returns: 0
m.isUnitary(1e-3) returns: 1
bool isUpperTriangular (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to an upper triangular matrix, within the precision given by prec.
See Also
isLowerTriangular()
bool isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const inherited
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Zero();
m(0,2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isZero() returns: " << m.isZero() << endl;
cout << "m.isZero(1e-3) returns: " << m.isZero(1e-3) << endl;
Output:
Here's the matrix m:
     0      0 0.0001
     0      0      0
     0      0      0
m.isZero() returns: 0
m.isZero(1e-3) returns: 1
See Also
class CwiseNullaryOp, Zero()
JacobiSVD< typename MatrixBase< Derived >::PlainObject > jacobiSvd (unsigned int computationOptions = 0) const
This is defined in the SVD module.
#include <Eigen/SVD>
Returns
the singular value decomposition of *this computed by two-sided Jacobi transformations.
See Also
class JacobiSVD
const LazyProductReturnType< Derived, OtherDerived >::Type lazyProduct (const MatrixBase< OtherDerived > & other) const
Returns
an expression of the matrix product of *this and other without implicit evaluation.
The returned product will behave like any other expressions: the coefficients of the product will be computed once at a time as requested. This might be useful in some extremely rare cases when only a small and no coherent fraction of the result's coefficients have to be computed.
Warning
This version of the matrix product can be much much slower. So use it only if you know what you are doing and that you measured a true speed improvement.
See Also
operator*(const MatrixBase&)
References Eigen::Dynamic.
const LDLT< typename MatrixBase< Derived >::PlainObject > ldlt () const inline
This is defined in the Cholesky module.
#include <Eigen/Cholesky>
Returns
the Cholesky decomposition with full pivoting without square root of *this
ColsBlockXpr leftCols (Index n) inline inherited
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols(2):" << endl;
cout << a.leftCols(2) << endl;
a.leftCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols(2):
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr leftCols (Index n) const inline inherited
This is the const version of leftCols(Index).
NColsBlockXpr<N>::Type leftCols (Index n = N) inline inherited
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols<2>():" << endl;
cout << a.leftCols<2>() << endl;
a.leftCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols<2>():
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type leftCols (Index n = N) const inline inherited
This is the const version of leftCols<int>().
const DenseBase< Derived >::SequentialLinSpacedReturnType LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) inline static inherited
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(Sequential,4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential,5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
const DenseBase< Derived >::RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar & low, const Scalar & high) inline static inherited
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
const DenseBase< Derived >::SequentialLinSpacedReturnType LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) inline static inherited
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(Sequential,4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential,5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
References DenseBase< Derived >::NullaryExpr().
const DenseBase< Derived >::RandomAccessLinSpacedReturnType LinSpaced (const Scalar & low, const Scalar & high) inline static inherited
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
References DenseBase< Derived >::NullaryExpr().
const LLT< typename MatrixBase< Derived >::PlainObject > llt () const inline
This is defined in the Cholesky module.
#include <Eigen/Cholesky>
Returns
the LLT decomposition of *this
NumTraits<typename internal::traits<Derived>::Scalar>::Real lpNorm () const inline
Returns
the norm of *this, that is, returns the p-th root of the sum of the p-th powers of the absolute values of the coefficients of *this. If p is the special value Eigen::Infinity, this function returns the norm, that is the maximum of the absolute values of the coefficients of *this.
See Also
norm()
const PartialPivLU< typename MatrixBase< Derived >::PlainObject > lu () const inline
This is defined in the LU module.
#include <Eigen/LU>
Synonym of partialPivLu().
Returns
the partial-pivoting LU decomposition of *this.
See Also
class PartialPivLU
void makeHouseholder (EssentialPart & essential, Scalar & tau, RealScalar & beta) const
Computes the elementary reflector H such that: where the transformation H is: and the vector v is:
On output:
Parameters
essential the essential part of the vector v
tau the scaling factor of the Householder transformation
beta the result of H * *this
See Also
MatrixBase::makeHouseholderInPlace(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
void makeHouseholderInPlace (Scalar & tau, RealScalar & beta)
Computes the elementary reflector H such that: where the transformation H is: and the vector v is:
The essential part of the vector v is stored in *this.
On output:
Parameters
tau the scaling factor of the Householder transformation
beta the result of H * *this
See Also
MatrixBase::makeHouseholder(), MatrixBase::applyHouseholderOnTheLeft(), MatrixBase::applyHouseholderOnTheRight()
internal::traits< Derived >::Scalar maxCoeff () const inline inherited
Returns
the maximum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
internal::traits< Derived >::Scalar maxCoeff (IndexType * rowPtr, IndexType * colPtr) const inherited
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See Also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
internal::traits< Derived >::Scalar maxCoeff (IndexType * index) const inherited
Returns
the maximum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See Also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
internal::traits< Derived >::Scalar mean () const inline inherited
Returns
the mean of all coefficients of *this
See Also
trace(), prod(), sum()
ColsBlockXpr middleCols (Index startCol, Index numCols) inline inherited
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleCols(1,3) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const inline inherited
This is the const version of middleCols(Index,Index).
NColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) inline inherited
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(:,1..3) =\n" << A.middleCols<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(:,1..3) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) const inline inherited
This is the const version of middleCols<int>().
RowsBlockXpr middleRows (Index startRow, Index n) inline inherited
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(2..3,:) =\n" << A.middleRows(2,2) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(2..3,:) =
 6  6 -3  5 -8
 6 -5  0 -8  6
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr middleRows (Index startRow, Index n) const inline inherited
This is the const version of middleRows(Index,Index).
NRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) inline inherited
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleRows<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-2 -3  3  3 -5
 6  6 -3  5 -8
 6 -5  0 -8  6
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) const inline inherited
This is the const version of middleRows<int>().
internal::traits< Derived >::Scalar minCoeff () const inline inherited
Returns
the minimum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
internal::traits< Derived >::Scalar minCoeff (IndexType * rowId, IndexType * colId) const inherited
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See Also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visitor(), DenseBase::minCoeff()
internal::traits< Derived >::Scalar minCoeff (IndexType * index) const inherited
Returns
the minimum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See Also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::minCoeff()
const NestByValue< Derived > nestByValue () const inline inherited
Returns
an expression of the temporary version of *this.
NoAlias< Derived, MatrixBase > noalias ()
Returns
a pseudo expression of *this with an operator= assuming no aliasing between *this and the source expression.
More precisely, noalias() allows to bypass the EvalBeforeAssignBit flag. Currently, even though several expressions may alias, only product expressions have this flag. Therefore, noalias() is only usefull when the source expression contains a matrix product.
Here are some examples where noalias is usefull:
* D.noalias()  = A * B;
* D.noalias() += A.transpose() * B;
* D.noalias() -= 2 * A * B.adjoint();
*
On the other hand the following example will lead to a wrong result:
* A.noalias() = A * B;
*
because the result matrix A is also an operand of the matrix product. Therefore, there is no alternative than evaluating A * B in a temporary, that is the default behavior when you write:
* A = A * B;
*
See Also
class NoAlias
Index nonZeros () const inline inherited
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
NumTraits< typename internal::traits< Derived >::Scalar >::Real norm () const inline
Returns
, for vectors, the l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the square root of the sum of the square of all the matrix entries. For vectors, this is also equals to the square root of the dot product of *this with itself.
See Also
dot(), squaredNorm()
void normalize () inline
Normalizes the vector, i.e. divides it by its own norm.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
norm(), normalized()
const MatrixBase< Derived >::PlainObject normalized () const inline
Returns
an expression of the quotient of *this by its own norm.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
norm(), normalize()
Referenced by QuaternionBase< Derived >::setFromTwoVectors().
const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) inline static inherited
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Referenced by DenseBase< Derived >::Constant(), MatrixBase< Derived >::Identity(), and DenseBase< Derived >::LinSpaced().
const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp & func) inline static inherited
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp & func) inline static inherited
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const DenseBase< Derived >::ConstantReturnType Ones (Index nbRows, Index nbCols) inline static inherited
Returns
an expression of a matrix where all coefficients equal one.
The parameters nbRows and nbCols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
cout << MatrixXi::Ones(2,3) << endl;
Output:
1 1 1
1 1 1
See Also
Ones(), Ones(Index), isOnes(), class Ones
const DenseBase< Derived >::ConstantReturnType Ones (Index newSize) inline static inherited
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
cout << 6 * RowVectorXi::Ones(4) << endl;
cout << VectorXf::Ones(2) << endl;
Output:
6 6 6 6
1
1
See Also
Ones(), Ones(Index,Index), isOnes(), class Ones
const DenseBase< Derived >::ConstantReturnType Ones () inline static inherited
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Ones() << endl;
cout << 6 * RowVector4i::Ones() << endl;
Output:
1 1
1 1
6 6 6 6
See Also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
bool operator!= (const MatrixBase< OtherDerived > & other) const inline
Returns
true if at least one pair of coefficients of *this and other are not exactly equal to each other.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See Also
isApprox(), operator==
const ScalarMultipleReturnType operator* (const Scalar & scalar) const inline
Returns
an expression of *this scaled by the scalar factor scalar
const CwiseUnaryOp<internal::scalar_multiple2_op<Scalar,std::complex<Scalar> >, const Derived> operator* (const std::complex< Scalar > & scalar) const inline
Overloaded for efficient real matrix times complex scalar value
const ProductReturnType< Derived, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > & other) const inline
Returns
the matrix product of *this and other.
Note
If instead of the matrix product you want the coefficient-wise product, see Cwise::operator*().
See Also
lazyProduct(), operator*=(const MatrixBase&), Cwise::operator*()
References Eigen::Dynamic.
const DiagonalProduct< Derived, DiagonalDerived, OnTheRight > operator* (const DiagonalBase< DiagonalDerived > & a_diagonal) const inline
Returns
the diagonal matrix product of *this by the diagonal matrix diagonal.
MatrixBase< Derived >::ScalarMultipleReturnType operator* (const UniformScaling< Scalar > & s) const
Concatenates a linear transformation matrix and a uniform scaling
Derived & operator*= (const EigenBase< OtherDerived > & other) inline
replaces *this by *this * other.
Returns
a reference to *this
Example:
Matrix3f A = Matrix3f::Random(3,3), B;
B << 0,1,0,
     0,0,1,
     1,0,0;
cout << "At start, A = " << endl << A << endl;
A *= B;
cout << "After A *= B, A = " << endl << A << endl;
A.applyOnTheRight(B);  // equivalent to A *= B
cout << "After applyOnTheRight, A = " << endl << A << endl;
Output:
At start, A =
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
After A *= B, A =
 -0.33   0.68  0.597
 0.536 -0.211  0.823
-0.444  0.566 -0.605
After applyOnTheRight, A =
 0.597  -0.33   0.68
 0.823  0.536 -0.211
-0.605 -0.444  0.566
References EigenBase< Derived >::derived().
const CwiseBinaryOp< internal::scalar_sum_op <Scalar>, const Derived, const OtherDerived> operator+ (const Eigen::MatrixBase< OtherDerived > & other) const
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See Also
class CwiseBinaryOp, operator+=()
Derived & operator+= (const MatrixBase< OtherDerived > & other) inline
replaces *this by *this + other.
Returns
a reference to *this
const CwiseBinaryOp< internal::scalar_difference_op <Scalar>, const Derived, const OtherDerived> operator- (const Eigen::MatrixBase< OtherDerived > & other) const
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See Also
class CwiseBinaryOp, operator-=()
const CwiseUnaryOp<internal::scalar_opposite_op<typename internal::traits<Derived>::Scalar>, const Derived> operator- () const inline
Returns
an expression of the opposite of *this
Derived & operator-= (const MatrixBase< OtherDerived > & other) inline
replaces *this by *this - other.
Returns
a reference to *this
const CwiseUnaryOp<internal::scalar_quotient1_op<typename internal::traits<Derived>::Scalar>, const Derived> operator/ (const Scalar & scalar) const inline
Returns
an expression of *this divided by the scalar value scalar
CommaInitializer< Derived > operator<< (const Scalar & s) inline inherited
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Matrix3i m1;
m1 << 1, 2, 3,
      4, 5, 6,
      7, 8, 9;
cout << m1 << endl << endl;
Matrix3i m2 = Matrix3i::Identity();
m2.block(0,0, 2,2) << 10, 11, 12, 13;
cout << m2 << endl << endl;
Vector2i v1;
v1 << 14, 15;
m2 << v1.transpose(), 16,
      v1, m1.block(1,1,2,2);
cout << m2 << endl;
Output:
1 2 3
4 5 6
7 8 9
10 11  0
12 13  0
 0  0  1
14 15 16
14  5  6
15  8  9
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See Also
CommaInitializer::finished(), class CommaInitializer
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > & other) inline inherited
See Also
operator<<(const Scalar&)
Derived & operator= (const MatrixBase< Derived > & other) inline
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
bool operator== (const MatrixBase< OtherDerived > & other) const inline
Returns
true if each coefficients of *this and other are all exactly equal.
Warning
When using floating point scalar values you probably should rather use a fuzzy comparison such as isApprox()
See Also
isApprox(), operator!=
MatrixBase< Derived >::RealScalar operatorNorm () const inline
Computes the L2 operator norm.
Returns
Operator norm of the matrix.
This is defined in the Eigenvalues module.
#include <Eigen/Eigenvalues>
This function computes the L2 operator norm of a matrix, which is also known as the spectral norm. The norm of a matrix is defined to be
where the maximum is over all vectors and the norm on the right is the Euclidean vector norm. The norm equals the largest singular value, which is the square root of the largest eigenvalue of the positive semi-definite matrix .
The current implementation uses the eigenvalues of , as computed by SelfAdjointView::eigenvalues(), to compute the operator norm of a matrix. The SelfAdjointView class provides a better algorithm for selfadjoint matrices.
Example:
MatrixXd ones = MatrixXd::Ones(3,3);
cout << "The operator norm of the 3x3 matrix of ones is "
     << ones.operatorNorm() << endl;
Output:
The operator norm of the 3x3 matrix of ones is 3
See Also
SelfAdjointView::eigenvalues(), SelfAdjointView::operatorNorm()
Index outerSize () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See Also
rows(), cols(), IsVectorAtCompileTime.
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
References DenseBase< Derived >::IsRowMajor, and DenseBase< Derived >::IsVectorAtCompileTime.
const PartialPivLU< typename MatrixBase< Derived >::PlainObject > partialPivLu () const inline
This is defined in the LU module.
#include <Eigen/LU>
Returns
the partial-pivoting LU decomposition of *this.
See Also
class PartialPivLU
internal::traits< Derived >::Scalar prod () const inline inherited
Returns
the product of all coefficients of *this
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the product of all the coefficients:" << endl << m.prod() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the product of all the coefficients:
0.0019
See Also
sum(), mean(), trace()
References Eigen::Dynamic.
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random (Index rows, Index cols) inline static inherited
Returns
a random matrix expression
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
cout << MatrixXi::Random(2,3) << endl;
Output:
 7  6  9
-2  6 -6
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index), MatrixBase::Random()
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random (Index size) inline static inherited
Returns
a random vector expression
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
cout << VectorXi::Random(2) << endl;
Output:
 7
-2
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random()
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random () inline static inherited
Returns
a fixed-size random matrix or vector expression
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << 100 * Matrix2i::Random() << endl;
Output:
 700  600
-200  600
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random(Index)
RealReturnType real () const inline
Returns
a read-only expression of the real part of *this.
See Also
imag()
NonConstRealReturnType real () inline
Returns
a non const expression of the real part of *this.
See Also
imag()
internal::result_of<Func(typename internal::traits<Derived>::Scalar)>::type redux (const Func & func) const inline inherited
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current STL and TR1 functor styles are handled.
See Also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
const Replicate< Derived, RowFactor, ColFactor > replicate () const inline inherited
Returns
an expression of the replication of *this
Example:
MatrixXi m = MatrixXi::Random(2,3);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "m.replicate<3,2>() = ..." << endl;
cout << m.replicate<3,2>() << endl;
Output:
Here is the matrix m:
 7  6  9
-2  6 -6
m.replicate<3,2>() = ...
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
See Also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
const DenseBase< Derived >::ReplicateReturnType replicate (Index rowFactor, Index colFactor) const inline inherited
Returns
an expression of the replication of *this
Example:
Vector3i v = Vector3i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "v.replicate(2,5) = ..." << endl;
cout << v.replicate(2,5) << endl;
Output:
Here is the vector v:
 7
-2
 6
v.replicate(2,5) = ...
 7  7  7  7  7
-2 -2 -2 -2 -2
 6  6  6  6  6
 7  7  7  7  7
-2 -2 -2 -2 -2
 6  6  6  6  6
See Also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
void resize (Index newSize) inline inherited
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
void resize (Index nbRows, Index nbCols) inline inherited
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
DenseBase< Derived >::ReverseReturnType reverse () inline inherited
Returns
an expression of the reverse of *this.
Example:
MatrixXi m = MatrixXi::Random(3,4);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the reverse of m:" << endl << m.reverse() << endl;
cout << "Here is the coefficient (1,0) in the reverse of m:" << endl
     << m.reverse()(1,0) << endl;
cout << "Let us overwrite this coefficient with the value 4." << endl;
m.reverse()(1,0) = 4;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  6 -3  1
-2  9  6  0
 6 -6 -5  3
Here is the reverse of m:
 3 -5 -6  6
 0  6  9 -2
 1 -3  6  7
Here is the coefficient (1,0) in the reverse of m:
0
Let us overwrite this coefficient with the value 4.
Now the matrix m is:
 7  6 -3  1
-2  9  6  4
 6 -6 -5  3
const DenseBase< Derived >::ConstReverseReturnType reverse () const inline inherited
This is the const version of reverse().
void reverseInPlace () inline inherited
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional features:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API allows to avoid creating a temporary (the current implementation creates a temporary, but that could be avoided using swap)
it allows future optimizations (cache friendliness, etc.)
See Also
reverse()
ColsBlockXpr rightCols (Index n) inline inherited
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols(2):" << endl;
cout << a.rightCols(2) << endl;
a.rightCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols(2):
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr rightCols (Index n) const inline inherited
This is the const version of rightCols(Index).
NColsBlockXpr<N>::Type rightCols (Index n = N) inline inherited
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols<2>():" << endl;
cout << a.rightCols<2>() << endl;
a.rightCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols<2>():
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type rightCols (Index n = N) const inline inherited
This is the const version of rightCols<int>().
RowXpr row (Index i) inline inherited
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.row(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 0 0
4 5 6
0 0 1
See Also
col(), class Block
Referenced by VectorwiseOp< ExpressionType, Direction >::cross(), and Transform< Scalar, Dim, Mode, _Options >::pretranslate().
ConstRowXpr row (Index i) const inline inherited
This is the const version of row().
const DenseBase< Derived >::ConstRowwiseReturnType rowwise () const inline inherited
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each row:" << endl << m.rowwise().sum() << endl;
cout << "Here is the maximum absolute value of each row:"
     << endl << m.cwiseAbs().rowwise().maxCoeff() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the sum of each row:
 0.948
  1.15
-0.483
Here is the maximum absolute value of each row:
 0.68
0.823
0.605
See Also
colwise(), class VectorwiseOp, Reductions, visitors and broadcasting
Referenced by Eigen::umeyama().
DenseBase< Derived >::RowwiseReturnType rowwise () inline inherited
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See Also
colwise(), class VectorwiseOp, Reductions, visitors and broadcasting
SegmentReturnType segment (Index start, Index n) inline inherited
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment(1, 2):" << endl << v.segment(1, 2) << endl;
v.segment(1, 2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment(1, 2):
-2  6
Now the vector v is:
7 0 0 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, segment(Index)
ConstSegmentReturnType segment (Index start, Index n) const inline inherited
This is the const version of segment(Index,Index).
FixedSegmentReturnType<N>::Type segment (Index start, Index n = N) inline inherited
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment<2>(1):" << endl << v.segment<2>(1) << endl;
v.segment<2>(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment<2>(1):
-2  6
Now the vector v is:
 7 -2  0  0
See Also
class Block
ConstFixedSegmentReturnType<N>::Type segment (Index start, Index n = N) const inline inherited
This is the const version of segment<int>(Index).
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline inherited
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
MatrixXi m(3, 3);
m << 1, 2, 3,
     4, 5, 6,
     7, 8, 9;
m = (m.array() >= 5).select(-m, m);
cout << m << endl;
Output:
 1  2  3
 4 -5 -6
-7 -8 -9
See Also
class Select
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > & thenMatrix, const typename ThenDerived::Scalar & elseScalar) const inline inherited
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See Also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline inherited
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See Also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
Derived & setConstant (const Scalar & val) inline inherited
Sets all coefficients in this expression to value.
See Also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
Derived & setIdentity () inline
Writes the identity expression (not necessarily square) into *this.
Example:
Matrix4i m = Matrix4i::Zero();
m.block<3,3>(1,0).setIdentity();
cout << m << endl;
Output:
0 0 0 0
1 0 0 0
0 1 0 0
0 0 1 0
See Also
class CwiseNullaryOp, Identity(), Identity(Index,Index), isIdentity()
Referenced by Transform< Scalar, Dim, Mode, _Options >::setIdentity().
Derived & setIdentity (Index nbRows, Index nbCols) inline
Resizes to the given size, and writes the identity expression (not necessarily square) into *this.
Parameters
nbRows the new number of rows
nbCols the new number of columns
Example:
MatrixXf m;
m.setIdentity(3, 3);
cout << m << endl;
Output:
1 0 0
0 1 0
0 0 1
See Also
MatrixBase::setIdentity(), class CwiseNullaryOp, MatrixBase::Identity()
Derived & setLinSpaced (Index newSize, const Scalar & low, const Scalar & high) inline inherited
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
VectorXf v;
v.setLinSpaced(5,0.5f,1.5f);
cout << v << endl;
Output:
 0.5
0.75
   1
1.25
 1.5
See Also
CwiseNullaryOp
Derived & setLinSpaced (const Scalar & low, const Scalar & high) inline inherited
Sets a linearly space vector.
The function fill *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
Derived & setOnes () inline inherited
Sets all coefficients in this expression to one.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setOnes();
cout << m << endl;
Output:
 7  9 -5 -3
 1  1  1  1
 6 -3  0  9
 6  6  3  9
See Also
class CwiseNullaryOp, Ones()
Derived & setRandom () inline inherited
Sets all coefficients in this expression to random values.
Example:
Matrix4i m = Matrix4i::Zero();
m.col(1).setRandom();
cout << m << endl;
Output:
 0  7  0  0
 0 -2  0  0
 0  6  0  0
 0  6  0  0
See Also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
Derived & setZero () inline inherited
Sets all coefficients in this expression to zero.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setZero();
cout << m << endl;
Output:
 7  9 -5 -3
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class CwiseNullaryOp, Zero()
Referenced by SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRows().
NumTraits< typename internal::traits< Derived >::Scalar >::Real squaredNorm () const inline
Returns
, for vectors, the squared l2 norm of *this, and for matrices the Frobenius norm. In both cases, it consists in the sum of the square of all the matrix entries. For vectors, this is also equals to the dot product of *this with itself.
See Also
dot(), norm()
NumTraits< typename internal::traits< Derived >::Scalar >::Real stableNorm () const inline
Returns
the l2 norm of *this avoiding underflow and overflow. This version use a blockwise two passes algorithm: 1 - find the absolute largest coefficient s 2 - compute in a standard way
For architecture/scalar types supporting vectorization, this version is faster than blueNorm(). Otherwise the blueNorm() is much faster.
See Also
norm(), blueNorm(), hypotNorm()
References Eigen::AlignedBit, and Eigen::DirectAccessBit.
internal::traits< Derived >::Scalar sum () const inline inherited
Returns
the sum of all coefficients of *this
See Also
trace(), prod(), mean()
References Eigen::Dynamic.
void swap (const DenseBase< OtherDerived > & other, int = OtherDerived::ThisConstantIsPrivateInPlainObjectBase) inline inherited
swaps *this with the expression other.
void swap (PlainObjectBase< OtherDerived > & other) inline inherited
swaps *this with the matrix or array other.
SegmentReturnType tail (Index n) inline inherited
Returns
a dynamic-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail(2) << endl;
v.tail(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
ConstSegmentReturnType tail (Index n) const inline inherited
This is the const version of tail(Index).
FixedSegmentReturnType<N>::Type tail (Index n = N) inline inherited
Returns
a fixed-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail<2>() << endl;
v.tail<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
See Also
class Block
ConstFixedSegmentReturnType<N>::Type tail (Index n = N) const inline inherited
This is the const version of tail<int>.
Block<Derived> topLeftCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner(2, 2):" << endl;
cout << m.topLeftCorner(2, 2) << endl;
m.topLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner(2, 2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> topLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topLeftCorner(Index, Index).
Block<Derived, CRows, CCols> topLeftCorner () inline inherited
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,2>():" << endl;
cout << m.topLeftCorner<2,2>() << endl;
m.topLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,2>():
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> topLeftCorner () const inline inherited
This is the const version of topLeftCorner<int, int>().
Block<Derived, CRows, CCols> topLeftCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,Dynamic>(2,2):" << endl;
cout << m.topLeftCorner<2,Dynamic>(2,2) << endl;
m.topLeftCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,Dynamic>(2,2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block
References DenseBase< Derived >::IsRowMajor, and DenseBase< Derived >::IsVectorAtCompileTime.
const Block<const Derived, CRows, CCols> topLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topLeftCorner<int, int>(Index, Index).
Block<Derived> topRightCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner(2, 2):" << endl;
cout << m.topRightCorner(2, 2) << endl;
m.topRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner(2, 2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> topRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topRightCorner(Index, Index).
Block<Derived, CRows, CCols> topRightCorner () inline inherited
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,2>():" << endl;
cout << m.topRightCorner<2,2>() << endl;
m.topRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,2>():
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block<int,int>(Index,Index)
const Block<const Derived, CRows, CCols> topRightCorner () const inline inherited
This is the const version of topRightCorner<int, int>().
Block<Derived, CRows, CCols> topRightCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,Dynamic>(2,2):" << endl;
cout << m.topRightCorner<2,Dynamic>(2,2) << endl;
m.topRightCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,Dynamic>(2,2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block
const Block<const Derived, CRows, CCols> topRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topRightCorner<int, int>(Index, Index).
RowsBlockXpr topRows (Index n) inline inherited
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows(2):" << endl;
cout << a.topRows(2) << endl;
a.topRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows(2):
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr topRows (Index n) const inline inherited
This is the const version of topRows(Index).
NRowsBlockXpr<N>::Type topRows (Index n = N) inline inherited
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows<2>():" << endl;
cout << a.topRows<2>() << endl;
a.topRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows<2>():
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type topRows (Index n = N) const inline inherited
This is the const version of topRows<int>().
internal::traits< Derived >::Scalar trace () const inline
Returns
the trace of *this, i.e. the sum of the coefficients on the main diagonal.
*this can be any matrix, not necessarily square.
See Also
diagonal(), sum()
Transpose< Derived > transpose () inline inherited
Returns
an expression of the transpose of *this.
Example:
Matrix2i m = Matrix2i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the transpose of m:" << endl << m.transpose() << endl;
cout << "Here is the coefficient (1,0) in the transpose of m:" << endl
     << m.transpose()(1,0) << endl;
cout << "Let us overwrite this coefficient with the value 0." << endl;
m.transpose()(1,0) = 0;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  6
-2  6
Here is the transpose of m:
 7 -2
 6  6
Here is the coefficient (1,0) in the transpose of m:
6
Let us overwrite this coefficient with the value 0.
Now the matrix m is:
 7  0
-2  6
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
* m = m.transpose(); // bug!!! caused by aliasing effect
*
Instead, use the transposeInPlace() method:
* m.transposeInPlace();
*
which gives Eigen good opportunities for optimization, or alternatively you can also do:
* m = m.transpose().eval();
*
See Also
transposeInPlace(), adjoint()
Referenced by Hyperplane< _Scalar, _AmbientDim, Options >::Through().
DenseBase< Derived >::ConstTransposeReturnType transpose () const inline inherited
This is the const version of transpose().
Make sure you read the warning for transpose() !
See Also
transposeInPlace(), adjoint()
void transposeInPlace () inline inherited
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
* m.transposeInPlace();
*
has the same effect on m as doing
* m = m.transpose().eval();
*
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See Also
transpose(), adjoint(), adjointInPlace()
References Eigen::Dynamic.
MatrixBase<Derived>::template TriangularViewReturnType<Mode>::Type triangularView ()
Returns
an expression of a triangular view extracted from the current matrix
The parameter Mode can have the following values: Upper, StrictlyUpper, UnitUpper, Lower, StrictlyLower, UnitLower.
Example:
#ifndef _MSC_VER
  #warning deprecated
#endif
/* deprecated
Matrix3i m = Matrix3i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the upper-triangular matrix extracted from m:" << endl
     << m.part<Eigen::UpperTriangular>() << endl;
cout << "Here is the strictly-upper-triangular matrix extracted from m:" << endl
     << m.part<Eigen::StrictlyUpperTriangular>() << endl;
cout << "Here is the unit-lower-triangular matrix extracted from m:" << endl
     << m.part<Eigen::UnitLowerTriangular>() << endl;
*/
Output:
See Also
class TriangularView
MatrixBase<Derived>::template ConstTriangularViewReturnType<Mode>::Type triangularView () const
This is the const version of MatrixBase::triangularView()
const CwiseUnaryOp<CustomUnaryOp, const Derived> unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define function to be applied coefficient-wise
double ramp(double x)
{
  if (x > 0)
    return x;
  else
    return 0;
}
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(ptr_fun(ramp)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
  0.68  0.823      0      0
     0      0  0.108 0.0268
 0.566      0      0  0.904
 0.597  0.536  0.258  0.832
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
const CwiseUnaryView<CustomViewOp, const Derived> unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
const MatrixBase< Derived >::BasisReturnType Unit (Index newSize, Index i) inline static
Returns
an expression of the i-th unit (basis) vector.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
MatrixBase::Unit(Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
const MatrixBase< Derived >::BasisReturnType Unit (Index i) inline static
Returns
an expression of the i-th unit (basis) vector.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is for fixed-size vector only.
See Also
MatrixBase::Unit(Index,Index), MatrixBase::UnitX(), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
MatrixBase< Derived >::PlainObject unitOrthogonal (void) const
Returns
a unit vector which is orthogonal to *this
The size of *this must be at least 2. If the size is exactly 2, then the returned vector is a counter clock wise rotation of *this, i.e., (-y,x).normalized().
See Also
cross()
const MatrixBase< Derived >::BasisReturnType UnitW () inline static
Returns
an expression of the W axis unit vector (0,0,0,1)
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
const MatrixBase< Derived >::BasisReturnType UnitX () inline static
Returns
an expression of the X axis unit vector (1{,0}^*)
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
const MatrixBase< Derived >::BasisReturnType UnitY () inline static
Returns
an expression of the Y axis unit vector (0,1{,0}^*)
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
const MatrixBase< Derived >::BasisReturnType UnitZ () inline static
Returns
an expression of the Z axis unit vector (0,0,1{,0}^*)
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
MatrixBase::Unit(Index,Index), MatrixBase::Unit(Index), MatrixBase::UnitY(), MatrixBase::UnitZ(), MatrixBase::UnitW()
CoeffReturnType value () const inline inherited
Returns
the unique coefficient of a 1x1 expression
Referenced by SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRows().
void visit (Visitor & visitor) const inherited
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
* struct MyVisitor {
*   // called for the first coefficient
*   void init(const Scalar& value, Index i, Index j);
*   // called for all other coefficients
*   void operator() (const Scalar& value, Index i, Index j);
* };
*
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See Also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
References Eigen::Dynamic.
const DenseBase< Derived >::ConstantReturnType Zero (Index nbRows, Index nbCols) inline static inherited
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
cout << MatrixXi::Zero(2,3) << endl;
Output:
0 0 0
0 0 0
See Also
Zero(), Zero(Index)
const DenseBase< Derived >::ConstantReturnType Zero (Index size) inline static inherited
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
cout << RowVectorXi::Zero(4) << endl;
cout << VectorXf::Zero(2) << endl;
Output:
0 0 0 0
0
0
See Also
Zero(), Zero(Index,Index)
const DenseBase< Derived >::ConstantReturnType Zero () inline static inherited
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Zero() << endl;
cout << RowVector4i::Zero() << endl;
Output:
0 0
0 0
0 0 0 0
See Also
Zero(Index), Zero(Index,Index)
Friends And Related Function Documentation
std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See Also
DenseBase::format()
The documentation for this class was generated from the following files:
MatrixBase.h
CommonCwiseUnaryOps.h
CommonCwiseBinaryOps.h
MatrixCwiseUnaryOps.h
MatrixCwiseBinaryOps.h
LDLT.h
LLT.h
Assign.h
CwiseBinaryOp.h
CwiseNullaryOp.h
Diagonal.h
DiagonalMatrix.h
DiagonalProduct.h
Dot.h
ForceAlignedAccess.h
GeneralProduct.h
NoAlias.h
PermutationMatrix.h
ProductBase.h
Redux.h
SelfAdjointView.h
StableNorm.h
Transpose.h
TriangularMatrix.h
MatrixBaseEigenvalues.h
EulerAngles.h
Homogeneous.h
OrthoMethods.h
Scaling.h
Householder.h
Jacobi.h
Determinant.h
FullPivLU.h
Inverse.h
PartialPivLU.h
ColPivHouseholderQR.h
FullPivHouseholderQR.h
HouseholderQR.h
SparseView.h
JacobiSVD.h