Eigen: HouseholderSequence< VectorsType, CoeffsType, Side > Class Template Reference
HouseholderSequence< VectorsType, CoeffsType, Side > Class Template Reference
Householder module
Detailed Description
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft>
class Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >
Sequence of Householder reflections acting on subspaces with decreasing size.
This is defined in the Householder module.
#include <Eigen/Householder>
Template Parameters
VectorsType type of matrix containing the Householder vectors
CoeffsType type of vector containing the Householder coefficients
Side either OnTheLeft (the default) or OnTheRight
This class represents a product sequence of Householder reflections where the first Householder reflection acts on the whole space, the second Householder reflection leaves the one-dimensional subspace spanned by the first unit vector invariant, the third Householder reflection leaves the two-dimensional subspace spanned by the first two unit vectors invariant, and so on up to the last reflection which leaves all but one dimensions invariant and acts only on the last dimension. Such sequences of Householder reflections are used in several algorithms to zero out certain parts of a matrix. Indeed, the methods HessenbergDecomposition::matrixQ(), Tridiagonalization::matrixQ(), HouseholderQR::householderQ(), and ColPivHouseholderQR::householderQ() all return a HouseholderSequence.
More precisely, the class HouseholderSequence represents an matrix of the form where the i-th Householder reflection is . The i-th Householder coefficient is a scalar and the i-th Householder vector is a vector of the form
The last entries of are called the essential part of the Householder vector.
Typical usages are listed below, where H is a HouseholderSequence:
* A.applyOnTheRight(H);             // A = A * H
* A.applyOnTheLeft(H);              // A = H * A
* A.applyOnTheRight(H.adjoint());   // A = A * H^*
* A.applyOnTheLeft(H.adjoint());    // A = H^* * A
* MatrixXd Q = H;                   // conversion to a dense matrix
*
In addition to the adjoint, you can also apply the inverse (=adjoint), the transpose, and the conjugate operators.
See the documentation for HouseholderSequence(const VectorsType&, const CoeffsType&) for an example.
See Also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Public Member Functions
ConjugateReturnType adjoint () const
Adjoint (conjugate transpose) of the Householder sequence.
Index cols () const
Number of columns of transformation viewed as a matrix.
ConjugateReturnType conjugate () const
Complex conjugate of the Householder sequence.
HouseholderSequence
< VectorsType, CoeffsType,
Side > & derived ()
const HouseholderSequence
< VectorsType, CoeffsType,
Side > & derived () const
const EssentialVectorType essentialVector (Index k) const
Essential part of a Householder vector.
HouseholderSequence (const VectorsType &v, const CoeffsType &h)
Constructor.
HouseholderSequence (const HouseholderSequence &other)
Copy constructor.
ConjugateReturnType inverse () const
Inverse of the Householder sequence (equals the adjoint).
Index length () const
Returns the length of the Householder sequence.
template<typename OtherDerived >
internal::matrix_type_times_scalar_type
< Scalar, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
Computes the product of a Householder sequence with a matrix.
Index rows () const
Number of rows of transformation viewed as a matrix.
HouseholderSequence & setLength (Index length)
Sets the length of the Householder sequence.
HouseholderSequence & setShift (Index shift)
Sets the shift of the Householder sequence.
Index shift () const
Returns the shift of the Householder sequence.
Index size () const
HouseholderSequence transpose () const
Transpose of the Householder sequence.
Protected Member Functions
HouseholderSequence & setTrans (bool trans)
Sets the transpose flag.
bool trans () const
Returns the transpose flag.
Constructor & Destructor Documentation
HouseholderSequence (const VectorsType & v, const CoeffsType & h) inline
Constructor.
Parameters
[in] v Matrix containing the essential parts of the Householder vectors
[in] h Vector containing the Householder coefficients
Constructs the Householder sequence with coefficients given by h and vectors given by v. The i-th Householder coefficient is given by h(i) and the essential part of the i-th Householder vector is given by v(k,i) with k > i (the subdiagonal part of the i-th column). If v has fewer columns than rows, then the Householder sequence contains as many Householder reflections as there are columns.
Note
The HouseholderSequence object stores v and h by reference.
Example:
Matrix3d v = Matrix3d::Random();
cout << "The matrix v is:" << endl;
cout << v << endl;
Vector3d v0(1, v(1,0), v(2,0));
cout << "The first Householder vector is: v_0 = " << v0.transpose() << endl;
Vector3d v1(0, 1, v(2,1));
cout << "The second Householder vector is: v_1 = " << v1.transpose()  << endl;
Vector3d v2(0, 0, 1);
cout << "The third Householder vector is: v_2 = " << v2.transpose() << endl;
Vector3d h = Vector3d::Random();
cout << "The Householder coefficients are: h = " << h.transpose() << endl;
Matrix3d H0 = Matrix3d::Identity() - h(0) * v0 * v0.adjoint();
cout << "The first Householder reflection is represented by H_0 = " << endl;
cout << H0 << endl;
Matrix3d H1 = Matrix3d::Identity() - h(1) * v1 * v1.adjoint();
cout << "The second Householder reflection is represented by H_1 = " << endl;
cout << H1 << endl;
Matrix3d H2 = Matrix3d::Identity() - h(2) * v2 * v2.adjoint();
cout << "The third Householder reflection is represented by H_2 = " << endl;
cout << H2 << endl;
cout << "Their product is H_0 H_1 H_2 = " << endl;
cout << H0 * H1 * H2 << endl;
HouseholderSequence<Matrix3d, Vector3d> hhSeq(v, h);
Matrix3d hhSeqAsMatrix(hhSeq);
cout << "If we construct a HouseholderSequence from v and h" << endl;
cout << "and convert it to a matrix, we get:" << endl;
cout << hhSeqAsMatrix << endl;
Output:
The matrix v is:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
The first Householder vector is: v_0 =      1 -0.211  0.566
The second Householder vector is: v_1 =      0      1 -0.605
The third Householder vector is: v_2 = 0 0 1
The Householder coefficients are: h =   0.108 -0.0452   0.258
The first Householder reflection is represented by H_0 =
  0.892  0.0228 -0.0611
 0.0228   0.995  0.0129
-0.0611  0.0129   0.965
The second Householder reflection is represented by H_1 =
      1       0       0
      0    1.05 -0.0273
      0 -0.0273    1.02
The third Householder reflection is represented by H_2 =
    1     0     0
    0     1     0
    0     0 0.742
Their product is H_0 H_1 H_2 =
  0.892  0.0255 -0.0466
 0.0228    1.04 -0.0105
-0.0611 -0.0129   0.728
If we construct a HouseholderSequence from v and h
and convert it to a matrix, we get:
  0.892  0.0255 -0.0466
 0.0228    1.04 -0.0105
-0.0611 -0.0129   0.728
See Also
setLength(), setShift()
Member Function Documentation
Index cols (void) const inline
Number of columns of transformation viewed as a matrix.
Returns
Number of columns
This equals the dimension of the space that the transformation acts on.
References HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
HouseholderSequence< VectorsType, CoeffsType, Side > & derived () inline inherited
Returns
a reference to the derived object
const HouseholderSequence< VectorsType, CoeffsType, Side > & derived () const inline inherited
Returns
a const reference to the derived object
const EssentialVectorType essentialVector (Index k) const inline
Essential part of a Householder vector.
Parameters
[in] k Index of Householder reflection
Returns
Vector containing non-trivial entries of k-th Householder vector
This function returns the essential part of the Householder vector . This is a vector of length containing the last entries of the vector
The index equals k + shift(), corresponding to the k-th column of the matrix v passed to the constructor.
See Also
setShift(), shift()
internal::matrix_type_times_scalar_type<Scalar, OtherDerived>::Type operator* (const MatrixBase< OtherDerived > & other) const inline
Computes the product of a Householder sequence with a matrix.
Parameters
[in] other Matrix being multiplied.
Returns
Expression object representing the product.
This function computes where is the Householder sequence represented by *this and is the matrix other.
Index rows (void) const inline
Number of rows of transformation viewed as a matrix.
Returns
Number of rows
This equals the dimension of the space that the transformation acts on.
References Eigen::OnTheLeft.
Referenced by HouseholderSequence< VectorsType, CoeffsType, Side >::cols().
HouseholderSequence& setLength (Index length) inline
Sets the length of the Householder sequence.
Parameters
[in] length New value for the length.
By default, the length of the Householder sequence is set to the number of columns of the matrix v passed to the constructor, or the number of rows if that is smaller. After this function is called, the length equals length.
See Also
length()
References HouseholderSequence< VectorsType, CoeffsType, Side >::length().
Referenced by HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate().
HouseholderSequence& setShift (Index shift) inline
Sets the shift of the Householder sequence.
Parameters
[in] shift New value for the shift.
By default, a HouseholderSequence object represents and the i-th column of the matrix v passed to the constructor corresponds to the i-th Householder reflection. After this function is called, the object represents and the i-th column of v corresponds to the (shift+i)-th Householder reflection.
See Also
shift()
References HouseholderSequence< VectorsType, CoeffsType, Side >::shift().
Referenced by HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate().
HouseholderSequence& setTrans (bool trans) inline protected
Sets the transpose flag.
Parameters
[in] trans New value of the transpose flag.
By default, the transpose flag is not set. If the transpose flag is set, then this object represents instead of .
See Also
trans()
References HouseholderSequence< VectorsType, CoeffsType, Side >::trans().
Referenced by HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), and HouseholderSequence< VectorsType, CoeffsType, Side >::transpose().
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols(), SizeAtCompileTime.
The documentation for this class was generated from the following files:
ForwardDeclarations.h
HouseholderSequence.h