Eigen: SparseMatrix< _Scalar, _Options, _Index > Class Template Reference
SparseMatrix< _Scalar, _Options, _Index > Class Template Reference
SparseCore module
Detailed Description
template<typename _Scalar, int _Options, typename _Index>
class Eigen::SparseMatrix< _Scalar, _Options, _Index >
A versatible sparse matrix representation.
This class implements a more versatile variants of the common compressed row/column storage format. Each colmun's (resp. row) non zeros are stored as a pair of value with associated row (resp. colmiun) index. All the non zeros are stored in a single large buffer. Unlike the compressed format, there might be extra space inbetween the nonzeros of two successive colmuns (resp. rows) such that insertion of new non-zero can be done with limited memory reallocation and copies.
A call to the function makeCompressed() turns the matrix into the standard compressed format compatible with many library.
More details on this storage sceheme are given in the manual pages.
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
_Options Union of bit flags controlling the storage scheme. Currently the only possibility is ColMajor or RowMajor. The default is 0 which means column-major.
_Index the type of the indices. It has to be a signed type (e.g., short, int, std::ptrdiff_t). Default is int.
This class can be extended with the help of the plugin mechanism described on the page Customizing/Extending Eigen by defining the preprocessor symbol EIGEN_SPARSEMATRIX_PLUGIN.
Public Member Functions
const CwiseBinaryOp
< CustomBinaryOp, const
SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > binaryExpr (const Eigen::SparseMatrixBase< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
Block< SparseMatrix< _Scalar,
_Options, _Index > > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index > > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index >, BlockRows,
BlockCols > block (Index startRow, Index startCol)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, BlockRows,
BlockCols > block (Index startRow, Index startCol) const
Block< SparseMatrix< _Scalar,
_Options, _Index >, BlockRows,
BlockCols > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, BlockRows,
BlockCols > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index > > bottomLeftCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index > > bottomLeftCorner (Index cRows, Index cCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomLeftCorner ()
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomLeftCorner () const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomLeftCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomLeftCorner (Index cRows, Index cCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index > > bottomRightCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index > > bottomRightCorner (Index cRows, Index cCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomRightCorner ()
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomRightCorner () const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomRightCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > bottomRightCorner (Index cRows, Index cCols) const
RowsBlockXpr bottomRows (Index n)
ConstRowsBlockXpr bottomRows (Index n) const
NRowsBlockXpr< N >::Type bottomRows (Index n=N)
ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
internal::cast_return_type
< SparseMatrix< _Scalar,
_Options, _Index >, const
CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar,
NewType >, const SparseMatrix
< _Scalar, _Options, _Index >
> >::type cast () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
ColXpr col (Index i)
ConstColXpr col (Index i) const
Index cols () const
ConjugateReturnType conjugate () const
void conservativeResize (Index rows, Index cols)
const CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseAbs () const
const CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseAbs2 () const
const CwiseBinaryOp
< std::equal_to< Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseEqual (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< std::binder1st
< std::equal_to< Scalar >
>, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseEqual (const Scalar &s) const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseInverse () const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMax (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMax (const Scalar &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMin (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMin (const Scalar &other) const
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseNotEqual (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_product_op
< typename SparseMatrix
< _Scalar, _Options, _Index >
::Scalar, typename
OtherDerived::Scalar >, const
SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseProduct (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseQuotient (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseSqrt () const
Derived & derived ()
const Derived & derived () const
const Diagonal< const
SparseMatrix > diagonal () const
const internal::eval
< SparseMatrix< _Scalar,
_Options, _Index > >::type eval () const
SegmentReturnType head (Index n)
ConstSegmentReturnType head (Index n) const
FixedSegmentReturnType< N >::Type head (Index n=N)
ConstFixedSegmentReturnType< N >
::Type head (Index n=N) const
const ImagReturnType imag () const
NonConstImagReturnType imag ()
const Index * innerIndexPtr () const
Index * innerIndexPtr ()
const Index * innerNonZeroPtr () const
Index * innerNonZeroPtr ()
Index innerSize () const
Scalar & insert (Index row, Index col)
bool isCompressed () const
bool isVector () const
ColsBlockXpr leftCols (Index n)
ConstColsBlockXpr leftCols (Index n) const
NColsBlockXpr< N >::Type leftCols (Index n=N)
ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
void makeCompressed ()
ColsBlockXpr middleCols (Index startCol, Index numCols)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
RowsBlockXpr middleRows (Index startRow, Index n)
ConstRowsBlockXpr middleRows (Index startRow, Index n) const
NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
Index nonZeros () const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const SparseMatrix
< _Scalar, _Options, _Index > > operator* (const std::complex< Scalar > &scalar) const
const
SparseDenseProductReturnType
< SparseMatrix< _Scalar,
_Options, _Index >
, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_sum_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > operator+ (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_difference_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > operator- (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index > > operator- () const
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index > > operator/ (const Scalar &scalar) const
const Index * outerIndexPtr () const
Index * outerIndexPtr ()
Index outerSize () const
void prune (const Scalar &reference, const RealScalar &epsilon=NumTraits< RealScalar >::dummy_precision())
template<typename KeepFunc >
void prune (const KeepFunc &keep=KeepFunc())
RealReturnType real () const
NonConstRealReturnType real ()
void reserve (Index reserveSize)
template<class SizesType >
void reserve (const SizesType &reserveSizes)
void resize (Index rows, Index cols)
ColsBlockXpr rightCols (Index n)
ConstColsBlockXpr rightCols (Index n) const
NColsBlockXpr< N >::Type rightCols (Index n=N)
ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
RowXpr row (Index i)
ConstRowXpr row (Index i) const
Index rows () const
SegmentReturnType segment (Index start, Index n)
ConstSegmentReturnType segment (Index start, Index n) const
FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
ConstFixedSegmentReturnType< N >
::Type segment (Index start, Index n=N) const
template<typename InputIterators >
void setFromTriplets (const InputIterators &begin, const InputIterators &end)
void setIdentity ()
void setZero ()
Index size () const
SparseMatrix ()
SparseMatrix (Index rows, Index cols)
template<typename OtherDerived >
SparseMatrix (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived , unsigned int UpLo>
SparseMatrix (const SparseSelfAdjointView< OtherDerived, UpLo > &other)
SparseMatrix (const SparseMatrix &other)
template<typename OtherDerived >
SparseMatrix (const ReturnByValue< OtherDerived > &other)
Copy constructor with in-place evaluation.
void swap (SparseMatrix &other)
SegmentReturnType tail (Index n)
ConstSegmentReturnType tail (Index n) const
FixedSegmentReturnType< N >::Type tail (Index n=N)
ConstFixedSegmentReturnType< N >
::Type tail (Index n=N) const
Block< SparseMatrix< _Scalar,
_Options, _Index > > topLeftCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index > > topLeftCorner (Index cRows, Index cCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topLeftCorner ()
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topLeftCorner () const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topLeftCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topLeftCorner (Index cRows, Index cCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index > > topRightCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index > > topRightCorner (Index cRows, Index cCols) const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topRightCorner ()
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topRightCorner () const
Block< SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topRightCorner (Index cRows, Index cCols)
const Block< const
SparseMatrix< _Scalar,
_Options, _Index >, CRows,
CCols > topRightCorner (Index cRows, Index cCols) const
RowsBlockXpr topRows (Index n)
ConstRowsBlockXpr topRows (Index n) const
NRowsBlockXpr< N >::Type topRows (Index n=N)
ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
SparseSymmetricPermutationProduct
< SparseMatrix< _Scalar,
_Options, _Index >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
const CwiseUnaryOp
< CustomUnaryOp, const
SparseMatrix< _Scalar,
_Options, _Index > > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
const CwiseUnaryView
< CustomViewOp, const
SparseMatrix< _Scalar,
_Options, _Index > > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
void uncompress ()
const Scalar * valuePtr () const
Scalar * valuePtr ()
~SparseMatrix ()
Constructor & Destructor Documentation
SparseMatrix () inline
Default constructor yielding an empty 0 x 0 matrix
SparseMatrix (Index rows, Index cols) inline
Constructs a rows x cols empty matrix
SparseMatrix (const SparseMatrixBase< OtherDerived > & other) inline
Constructs a sparse matrix from the sparse expression other
SparseMatrix (const SparseSelfAdjointView< OtherDerived, UpLo > & other) inline
Constructs a sparse matrix from the sparse selfadjoint view other
SparseMatrix (const SparseMatrix< _Scalar, _Options, _Index > & other) inline
Copy constructor (it performs a deep copy)
~SparseMatrix () inline
Destructor
Member Function Documentation
const CwiseBinaryOp<CustomBinaryOp, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> binaryExpr (const Eigen::SparseMatrixBase< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline inherited
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template binary functor
template<typename Scalar> struct MakeComplexOp {
  EIGEN_EMPTY_STRUCT_CTOR(MakeComplexOp)
  typedef complex<Scalar> result_type;
  complex<Scalar> operator()(const Scalar& a, const Scalar& b) const { return complex<Scalar>(a,b); }
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random(), m2 = Matrix4d::Random();
  cout << m1.binaryExpr(m2, MakeComplexOp<double>()) << endl;
  return 0;
}
Output:
   (0.68,0.271)  (0.823,-0.967) (-0.444,-0.687)   (-0.27,0.998)
 (-0.211,0.435) (-0.605,-0.514)  (0.108,-0.198) (0.0268,-0.563)
 (0.566,-0.717)  (-0.33,-0.726) (-0.0452,-0.74)  (0.904,0.0259)
  (0.597,0.214)   (0.536,0.608)  (0.258,-0.782)   (0.832,0.678)
See Also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
Block<SparseMatrix< _Scalar, _Options, _Index > > block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline inherited
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block(1, 1, 2, 2):" << endl << m.block(1, 1, 2, 2) << endl;
m.block(1, 1, 2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block(1, 1, 2, 2):
-6  1
-3  0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline inherited
This is the const version of block(Index,Index,Index,Index).
Block<SparseMatrix< _Scalar, _Options, _Index > , BlockRows, BlockCols> block (Index startRow, Index startCol) inline inherited
Returns
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block<2,2>(1,1):" << endl << m.block<2,2>(1,1) << endl;
m.block<2,2>(1,1).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block<2,2>(1,1):
-6  1
-3  0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > , BlockRows, BlockCols> block (Index startRow, Index startCol) const inline inherited
This is the const version of block<>(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > , BlockRows, BlockCols> block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline inherited
Returns
an expression of a block in *this.
Template Parameters
BlockRows number of rows in block as specified at compile-time
BlockCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal BlockRows unless BlockRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the block:" << endl << m.block<2, Dynamic>(1, 1, 2, 3) << endl;
m.block<2, Dynamic>(1, 1, 2, 3).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the block:" << endl << m.block<2, Dynamic>(1, 1, 2, 3) << endl;
m.block<2, Dynamic>(1, 1, 2, 3).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > , BlockRows, BlockCols> block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline inherited
This is the const version of block<>(Index, Index, Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > > bottomLeftCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner(2, 2):" << endl;
cout << m.bottomLeftCorner(2, 2) << endl;
m.bottomLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner(2, 2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > > bottomLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomLeftCorner(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomLeftCorner () inline inherited
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,2>():" << endl;
cout << m.bottomLeftCorner<2,2>() << endl;
m.bottomLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,2>():
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomLeftCorner () const inline inherited
This is the const version of bottomLeftCorner<int, int>().
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomLeftCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,Dynamic>(2,2):" << endl;
cout << m.bottomLeftCorner<2,Dynamic>(2,2) << endl;
m.bottomLeftCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,Dynamic>(2,2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomLeftCorner<int, int>(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > > bottomRightCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner(2, 2):" << endl;
cout << m.bottomRightCorner(2, 2) << endl;
m.bottomRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner(2, 2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > > bottomRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomRightCorner(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomRightCorner () inline inherited
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,2>():" << endl;
cout << m.bottomRightCorner<2,2>() << endl;
m.bottomRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,2>():
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomRightCorner () const inline inherited
This is the const version of bottomRightCorner<int, int>().
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomRightCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,Dynamic>(2,2):" << endl;
cout << m.bottomRightCorner<2,Dynamic>(2,2) << endl;
m.bottomRightCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,Dynamic>(2,2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> bottomRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of bottomRightCorner<int, int>(Index, Index).
RowsBlockXpr bottomRows (Index n) inline inherited
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows(2):" << endl;
cout << a.bottomRows(2) << endl;
a.bottomRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows(2):
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr bottomRows (Index n) const inline inherited
This is the const version of bottomRows(Index).
NRowsBlockXpr<N>::Type bottomRows (Index n = N) inline inherited
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows<2>():" << endl;
cout << a.bottomRows<2>() << endl;
a.bottomRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows<2>():
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type bottomRows (Index n = N) const inline inherited
This is the const version of bottomRows<int>().
internal::cast_return_type<SparseMatrix< _Scalar, _Options, _Index > ,const CwiseUnaryOp<internal::scalar_cast_op<typename internal::traits<SparseMatrix< _Scalar, _Options, _Index > >::Scalar, NewType>, const SparseMatrix< _Scalar, _Options, _Index > > >::type cast () const inline inherited
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See Also
class CwiseUnaryOp
Scalar coeff (Index row, Index col) const inline
Returns
the value of the matrix at position i, j This function returns Scalar(0) if the element is an explicit zero
Scalar& coeffRef (Index row, Index col) inline
Returns
a non-const reference to the value of the matrix at position i, j
If the element does not exist then it is inserted via the insert(Index,Index) function which itself turns the matrix into a non compressed form if that was not the case.
This is a O(log(nnz_j)) operation (binary search) plus the cost of insert(Index,Index) function if the element does not already exist.
ColXpr col (Index i) inline inherited
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.col(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 4 0
0 5 0
0 6 1
See Also
row(), class Block
Referenced by SparseMatrix< Scalar, RowMajor >::coeff(), and SparseMatrix< Scalar, RowMajor >::coeffRef().
ConstColXpr col (Index i) const inline inherited
This is the const version of col().
Index cols (void) const inline
Returns
the number of columns of the matrix
Referenced by SparseMatrix< Scalar, RowMajor >::coeff(), SparseMatrix< Scalar, RowMajor >::coeffRef(), SparseQR< MatrixType, OrderingType >::cols(), SparseMatrix< Scalar, RowMajor >::conservativeResize(), SparseMatrix< Scalar, RowMajor >::insert(), SparseMatrix< Scalar, RowMajor >::resize(), SparseMatrix< Scalar, RowMajor >::setIdentity(), and Eigen::viewAsCholmod().
ConjugateReturnType conjugate () const inline inherited
Returns
an expression of the complex conjugate of *this.
See Also
adjoint()
void conservativeResize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix leaving old values untouched.
See Also
resizeNonZeros(Index), reserve(), setZero()
const CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > > cwiseAbs () const inline inherited
Returns
an expression of the coefficient-wise absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs() << endl;
Output:
2 4 6
5 1 0
See Also
cwiseAbs2()
const CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > > cwiseAbs2 () const inline inherited
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs2() << endl;
Output:
 4 16 36
25  1  0
See Also
cwiseAbs()
const CwiseBinaryOp<std::equal_to<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> cwiseEqual (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise == operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are equal: " << count << endl;
Output:
Comparing m with identity matrix:
1 1
0 1
Number of coefficients that are equal: 3
See Also
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
const CwiseUnaryOp<std::binder1st<std::equal_to<Scalar> >, const SparseMatrix< _Scalar, _Options, _Index > > cwiseEqual (const Scalar & s) const inline inherited
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See Also
cwiseEqual(const MatrixBase<OtherDerived> &) const
const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > > cwiseInverse () const inline inherited
Returns
an expression of the coefficient-wise inverse of *this.
Example:
MatrixXd m(2,3);
m << 2, 0.5, 1,
     3, 0.25, 1;
cout << m.cwiseInverse() << endl;
Output:
  0.5     2     1
0.333     4     1
See Also
cwiseProduct()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> cwiseMax (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise max of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMax(w) << endl;
Output:
4
3
4
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const ConstantReturnType> cwiseMax (const Scalar & other) const inline inherited
Returns
an expression of the coefficient-wise max of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> cwiseMin (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise min of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMin(w) << endl;
Output:
2
2
3
See Also
class CwiseBinaryOp, max()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const ConstantReturnType> cwiseMin (const Scalar & other) const inline inherited
Returns
an expression of the coefficient-wise min of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<std::not_equal_to<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> cwiseNotEqual (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseNotEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseNotEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are not equal: " << count << endl;
Output:
Comparing m with identity matrix:
0 0
1 0
Number of coefficients that are not equal: 1
See Also
cwiseEqual(), isApprox(), isMuchSmallerThan()
const CwiseBinaryOp<internal::scalar_product_op<typename SparseMatrix< _Scalar, _Options, _Index > ::Scalar, typename OtherDerived ::Scalar >, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived > cwiseProduct (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Matrix3i a = Matrix3i::Random(), b = Matrix3i::Random();
Matrix3i c = a.cwiseProduct(b);
cout << "a:\n" << a << "\nb:\n" << b << "\nc:\n" << c << endl;
Output:
a:
 7  6 -3
-2  9  6
 6 -6 -5
b:
 1 -3  9
 0  0  3
 3  9  5
c:
  7 -18 -27
  0   0  18
 18 -54 -25
See Also
class CwiseBinaryOp, cwiseAbs2
const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> cwiseQuotient (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseQuotient(w) << endl;
Output:
 0.5
 1.5
1.33
See Also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
const CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const SparseMatrix< _Scalar, _Options, _Index > > cwiseSqrt () const inline inherited
Returns
an expression of the coefficient-wise square root of *this.
Example:
Vector3d v(1,2,4);
cout << v.cwiseSqrt() << endl;
Output:
   1
1.41
   2
See Also
cwisePow(), cwiseSquare()
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by MatrixBase< Derived >::applyOnTheLeft(), MatrixBase< Derived >::applyOnTheRight(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), RotationBase< Derived, 3 >::operator*(), SparseSelfAdjointView< MatrixType, UpLo >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), SparseMatrixBase< Derived >::operator*(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), Transform< Scalar, Dim, Mode, _Options >::operator*(), Eigen::operator*(), MatrixBase< Derived >::operator*=(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), DenseBase< Derived >::operator=(), Transform< Scalar, Dim, Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), SparseLU< _MatrixType, _OrderingType >::solve(), UmfPackLU< _MatrixType >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::toDenseMatrix(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRows(), Transform< Scalar, Dim, Mode, _Options >::Transform(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::unaryViewExpr().
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
const Diagonal<const SparseMatrix> diagonal () const inline
Returns
a const expression of the diagonal coefficients
const internal::eval<SparseMatrix< _Scalar, _Options, _Index > >::type eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
SegmentReturnType head (Index n) inline inherited
Returns
a dynamic-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head(2) << endl;
v.head(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
ConstSegmentReturnType head (Index n) const inline inherited
This is the const version of head(Index).
FixedSegmentReturnType<N>::Type head (Index n = N) inline inherited
Returns
a fixed-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head<2>() << endl;
v.head<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
See Also
class Block
ConstFixedSegmentReturnType<N>::Type head (Index n = N) const inline inherited
This is the const version of head<int>().
const ImagReturnType imag () const inline inherited
Returns
an read-only expression of the imaginary part of *this.
See Also
real()
NonConstImagReturnType imag () inline inherited
Returns
a non const expression of the imaginary part of *this.
See Also
real()
const Index* innerIndexPtr () const inline
Returns
a const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), outerIndexPtr()
Referenced by Eigen::viewAsCholmod().
Index* innerIndexPtr () inline
Returns
a non-const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), outerIndexPtr()
const Index* innerNonZeroPtr () const inline
Returns
a const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
Referenced by Eigen::viewAsCholmod().
Index* innerNonZeroPtr () inline
Returns
a non-const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
Index innerSize () const inline
Returns
the number of rows (resp. columns) of the matrix if the storage order column major (resp. row major)
Scalar& insert (Index row, Index col) inline
Returns
a reference to a novel non zero coefficient with coordinates row x col. The non zero coefficient must not already exist.
If the matrix *this is in compressed mode, then *this is turned into uncompressed mode while reserving room for 2 non zeros per inner vector. It is strongly recommended to first call reserve(const SizesType &) to reserve a more appropriate number of elements per inner vector that better match your scenario.
This function performs a sorted insertion in O(1) if the elements of each inner vector are inserted in increasing inner index order, and in O(nnz_j) for a random insertion.
Referenced by SparseMatrix< Scalar, RowMajor >::coeffRef().
bool isCompressed () const inline
Returns
whether *this is in compressed form.
Referenced by SparseMatrix< Scalar, RowMajor >::insert(), SparseMatrix< Scalar, RowMajor >::makeCompressed(), SparseMatrix< Scalar, RowMajor >::reserve(), and Eigen::viewAsCholmod().
bool isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See Also
rows(), cols(), IsVectorAtCompileTime.
ColsBlockXpr leftCols (Index n) inline inherited
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols(2):" << endl;
cout << a.leftCols(2) << endl;
a.leftCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols(2):
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr leftCols (Index n) const inline inherited
This is the const version of leftCols(Index).
NColsBlockXpr<N>::Type leftCols (Index n = N) inline inherited
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols<2>():" << endl;
cout << a.leftCols<2>() << endl;
a.leftCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols<2>():
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type leftCols (Index n = N) const inline inherited
This is the const version of leftCols<int>().
void makeCompressed () inline
Turns the matrix into the compressed format.
Referenced by SparseMatrix< Scalar, RowMajor >::prune().
ColsBlockXpr middleCols (Index startCol, Index numCols) inline inherited
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleCols(1,3) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const inline inherited
This is the const version of middleCols(Index,Index).
NColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) inline inherited
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(:,1..3) =\n" << A.middleCols<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(:,1..3) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) const inline inherited
This is the const version of middleCols<int>().
RowsBlockXpr middleRows (Index startRow, Index n) inline inherited
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(2..3,:) =\n" << A.middleRows(2,2) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(2..3,:) =
 6  6 -3  5 -8
 6 -5  0 -8  6
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr middleRows (Index startRow, Index n) const inline inherited
This is the const version of middleRows(Index,Index).
NRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) inline inherited
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleRows<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-2 -3  3  3 -5
 6  6 -3  5 -8
 6 -5  0 -8  6
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) const inline inherited
This is the const version of middleRows<int>().
Index nonZeros () const inline
Returns
the number of non zero coefficients
Referenced by Eigen::viewAsCholmod().
const ScalarMultipleReturnType operator* (const Scalar & scalar) const inline inherited
Returns
an expression of *this scaled by the scalar factor scalar
const CwiseUnaryOp<internal::scalar_multiple2_op<Scalar,std::complex<Scalar> >, const SparseMatrix< _Scalar, _Options, _Index > > operator* (const std::complex< Scalar > & scalar) const inline inherited
Overloaded for efficient real matrix times complex scalar value
const SparseDenseProductReturnType<SparseMatrix< _Scalar, _Options, _Index > ,OtherDerived>::Type operator* (const MatrixBase< OtherDerived > & other) const inline inherited
sparse * dense (returns a dense object unless it is an outer product)
const CwiseBinaryOp< internal::scalar_sum_op <Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> operator+ (const Eigen::SparseMatrixBase< OtherDerived > & other) const inherited
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See Also
class CwiseBinaryOp, operator+=()
const CwiseBinaryOp< internal::scalar_difference_op <Scalar>, const SparseMatrix< _Scalar, _Options, _Index > , const OtherDerived> operator- (const Eigen::SparseMatrixBase< OtherDerived > & other) const inherited
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See Also
class CwiseBinaryOp, operator-=()
const CwiseUnaryOp<internal::scalar_opposite_op<typename internal::traits<SparseMatrix< _Scalar, _Options, _Index > >::Scalar>, const SparseMatrix< _Scalar, _Options, _Index > > operator- () const inline inherited
Returns
an expression of the opposite of *this
const CwiseUnaryOp<internal::scalar_quotient1_op<typename internal::traits<SparseMatrix< _Scalar, _Options, _Index > >::Scalar>, const SparseMatrix< _Scalar, _Options, _Index > > operator/ (const Scalar & scalar) const inline inherited
Returns
an expression of *this divided by the scalar value scalar
const Index* outerIndexPtr () const inline
Returns
a const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), innerIndexPtr()
Referenced by Eigen::viewAsCholmod().
Index* outerIndexPtr () inline
Returns
a non-const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), innerIndexPtr()
Index outerSize () const inline
Returns
the number of columns (resp. rows) of the matrix if the storage order column major (resp. row major)
Referenced by SparseMatrix< Scalar, RowMajor >::insert(), and SparseMatrix< Scalar, RowMajor >::resize().
void prune (const Scalar & reference, const RealScalar & epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Suppresses all nonzeros which are much smaller than reference under the tolerence epsilon
Referenced by SparseMatrix< Scalar, RowMajor >::prune().
void prune (const KeepFunc & keep = KeepFunc()) inline
Turns the matrix into compressed format, and suppresses all nonzeros which do not satisfy the predicate keep. The functor type KeepFunc must implement the following function:
* bool operator() (const Index& row, const Index& col, const Scalar& value) const;
*
See Also
prune(Scalar,RealScalar)
RealReturnType real () const inline inherited
Returns
a read-only expression of the real part of *this.
See Also
imag()
NonConstRealReturnType real () inline inherited
Returns
a non const expression of the real part of *this.
See Also
imag()
void reserve (Index reserveSize) inline
Preallocates reserveSize non zeros.
Precondition: the matrix must be in compressed mode.
Referenced by SparseMatrix< Scalar, RowMajor >::insert().
void reserve (const SizesType & reserveSizes) inline
Preallocates reserveSize[j] non zeros for each column (resp. row) j.
This function turns the matrix in non-compressed mode
void resize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix and initializes it to zero.
See Also
resizeNonZeros(Index), reserve(), setZero()
Referenced by SparseMatrix< Scalar, RowMajor >::conservativeResize(), and SparseMatrix< Scalar, RowMajor >::SparseMatrix().
ColsBlockXpr rightCols (Index n) inline inherited
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols(2):" << endl;
cout << a.rightCols(2) << endl;
a.rightCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols(2):
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr rightCols (Index n) const inline inherited
This is the const version of rightCols(Index).
NColsBlockXpr<N>::Type rightCols (Index n = N) inline inherited
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols<2>():" << endl;
cout << a.rightCols<2>() << endl;
a.rightCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols<2>():
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type rightCols (Index n = N) const inline inherited
This is the const version of rightCols<int>().
RowXpr row (Index i) inline inherited
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.row(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 0 0
4 5 6
0 0 1
See Also
col(), class Block
Referenced by SparseMatrix< Scalar, RowMajor >::coeff(), and SparseMatrix< Scalar, RowMajor >::coeffRef().
ConstRowXpr row (Index i) const inline inherited
This is the const version of row().
Index rows (void) const inline
Returns
the number of rows of the matrix
Referenced by SparseMatrix< Scalar, RowMajor >::coeff(), SparseMatrix< Scalar, RowMajor >::coeffRef(), SparseMatrix< Scalar, RowMajor >::conservativeResize(), SparseMatrix< Scalar, RowMajor >::insert(), SparseMatrix< Scalar, RowMajor >::resize(), SparseQR< MatrixType, OrderingType >::rows(), SparseMatrix< Scalar, RowMajor >::setIdentity(), and Eigen::viewAsCholmod().
SegmentReturnType segment (Index start, Index n) inline inherited
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment(1, 2):" << endl << v.segment(1, 2) << endl;
v.segment(1, 2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment(1, 2):
-2  6
Now the vector v is:
7 0 0 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, segment(Index)
ConstSegmentReturnType segment (Index start, Index n) const inline inherited
This is the const version of segment(Index,Index).
FixedSegmentReturnType<N>::Type segment (Index start, Index n = N) inline inherited
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment<2>(1):" << endl << v.segment<2>(1) << endl;
v.segment<2>(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment<2>(1):
-2  6
Now the vector v is:
 7 -2  0  0
See Also
class Block
ConstFixedSegmentReturnType<N>::Type segment (Index start, Index n = N) const inline inherited
This is the const version of segment<int>(Index).
void setFromTriplets (const InputIterators & begin, const InputIterators & end)
Fill the matrix *this with the list of triplets defined by the iterator range begin - end.
A triplet is a tuple (i,j,value) defining a non-zero element. The input list of triplets does not have to be sorted, and can contains duplicated elements. In any case, the result is a sorted and compressed sparse matrix where the duplicates have been summed up. This is a O(n) operation, with n the number of triplet elements. The initial contents of *this is destroyed. The matrix *this must be properly resized beforehand using the SparseMatrix(Index,Index) constructor, or the resize(Index,Index) method. The sizes are not extracted from the triplet list.
The InputIterators value_type must provide the following interface:
* Scalar value() const; // the value
* Scalar row() const;   // the row index i
* Scalar col() const;   // the column index j
*
See for instance the Eigen::Triplet template class.
Here is a typical usage example:
  typedef Triplet<double> T;
  std::vector<T> tripletList;
  triplets.reserve(estimation_of_entries);
  for(...)
  {
    // ...
    tripletList.push_back(T(i,j,v_ij));
  }
  SparseMatrixType m(rows,cols);
  m.setFromTriplets(tripletList.begin(), tripletList.end());
  // m is ready to go!
*
Warning
The list of triplets is read multiple times (at least twice). Therefore, it is not recommended to define an abstract iterator over a complex data-structure that would be expensive to evaluate. The triplets should rather be explicitely stored into a std::vector for instance.
void setIdentity () inline
Sets *this to the identity matrix
void setZero () inline
Removes all non zeros but keep allocated memory
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols().
void swap (SparseMatrix< _Scalar, _Options, _Index > & other) inline
Swaps the content of two sparse matrices of the same type. This is a fast operation that simply swaps the underlying pointers and parameters.
SegmentReturnType tail (Index n) inline inherited
Returns
a dynamic-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail(2) << endl;
v.tail(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
ConstSegmentReturnType tail (Index n) const inline inherited
This is the const version of tail(Index).
FixedSegmentReturnType<N>::Type tail (Index n = N) inline inherited
Returns
a fixed-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail<2>() << endl;
v.tail<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
See Also
class Block
ConstFixedSegmentReturnType<N>::Type tail (Index n = N) const inline inherited
This is the const version of tail<int>.
Block<SparseMatrix< _Scalar, _Options, _Index > > topLeftCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner(2, 2):" << endl;
cout << m.topLeftCorner(2, 2) << endl;
m.topLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner(2, 2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > > topLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topLeftCorner(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topLeftCorner () inline inherited
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,2>():" << endl;
cout << m.topLeftCorner<2,2>() << endl;
m.topLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,2>():
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topLeftCorner () const inline inherited
This is the const version of topLeftCorner<int, int>().
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topLeftCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,Dynamic>(2,2):" << endl;
cout << m.topLeftCorner<2,Dynamic>(2,2) << endl;
m.topLeftCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,Dynamic>(2,2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topLeftCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topLeftCorner<int, int>(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > > topRightCorner (Index cRows, Index cCols) inline inherited
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner(2, 2):" << endl;
cout << m.topRightCorner(2, 2) << endl;
m.topRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner(2, 2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > > topRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topRightCorner(Index, Index).
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topRightCorner () inline inherited
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,2>():" << endl;
cout << m.topRightCorner<2,2>() << endl;
m.topRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,2>():
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block<int,int>(Index,Index)
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topRightCorner () const inline inherited
This is the const version of topRightCorner<int, int>().
Block<SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topRightCorner (Index cRows, Index cCols) inline inherited
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,Dynamic>(2,2):" << endl;
cout << m.topRightCorner<2,Dynamic>(2,2) << endl;
m.topRightCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,Dynamic>(2,2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block
const Block<const SparseMatrix< _Scalar, _Options, _Index > , CRows, CCols> topRightCorner (Index cRows, Index cCols) const inline inherited
This is the const version of topRightCorner<int, int>(Index, Index).
RowsBlockXpr topRows (Index n) inline inherited
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows(2):" << endl;
cout << a.topRows(2) << endl;
a.topRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows(2):
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr topRows (Index n) const inline inherited
This is the const version of topRows(Index).
NRowsBlockXpr<N>::Type topRows (Index n = N) inline inherited
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows<2>():" << endl;
cout << a.topRows<2>() << endl;
a.topRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows<2>():
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type topRows (Index n = N) const inline inherited
This is the const version of topRows<int>().
SparseSymmetricPermutationProduct<SparseMatrix< _Scalar, _Options, _Index > ,Upper|Lower> twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
const CwiseUnaryOp<CustomUnaryOp, const SparseMatrix< _Scalar, _Options, _Index > > unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline inherited
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define function to be applied coefficient-wise
double ramp(double x)
{
  if (x > 0)
    return x;
  else
    return 0;
}
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(ptr_fun(ramp)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
  0.68  0.823      0      0
     0      0  0.108 0.0268
 0.566      0      0  0.904
 0.597  0.536  0.258  0.832
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
const CwiseUnaryView<CustomViewOp, const SparseMatrix< _Scalar, _Options, _Index > > unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline inherited
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
void uncompress () inline
Turns the matrix into the uncompressed mode
const Scalar* valuePtr () const inline
Returns
a const pointer to the array of values. This function is aimed at interoperability with other libraries.
See Also
innerIndexPtr(), outerIndexPtr()
Referenced by Eigen::viewAsCholmod().
Scalar* valuePtr () inline
Returns
a non-const pointer to the array of values. This function is aimed at interoperability with other libraries.
See Also
innerIndexPtr(), outerIndexPtr()
The documentation for this class was generated from the following file:
SparseMatrix.h