Eigen: Eigen Namespace Reference
Eigen Namespace Reference
Namespace containing all symbols from the Eigen library.
Namespaces
internal
Classes
class aligned_allocator
STL compatible allocator to use with with 16 byte aligned types.
class AlignedBox
An axis aligned box.
class AMDOrdering
class AngleAxis
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
class Array
General-purpose arrays with easy API for coefficient-wise operations.
class ArrayBase
Base class for all 1D and 2D array, and related expressions.
class ArrayWrapper
Expression of a mathematical vector or matrix as an array object.
struct ArrayXpr
class BiCGSTAB
A bi conjugate gradient stabilized solver for sparse square problems.
class Block
Expression of a fixed-size or dynamic-size block.
class BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >
class CholmodBase
The base class for the direct Cholesky factorization of Cholmod.
class CholmodDecomposition
A general Cholesky factorization and solver based on Cholmod.
class CholmodSimplicialLDLT
A simplicial direct Cholesky (LDLT) factorization and solver based on Cholmod.
class CholmodSimplicialLLT
A simplicial direct Cholesky (LLT) factorization and solver based on Cholmod.
class CholmodSupernodalLLT
A supernodal Cholesky (LLT) factorization and solver based on Cholmod.
class COLAMDOrdering
class ColPivHouseholderQR
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
class CommaInitializer
Helper class used by the comma initializer operator.
class ComplexEigenSolver
Computes eigenvalues and eigenvectors of general complex matrices.
class ComplexSchur
Performs a complex Schur decomposition of a real or complex square matrix.
class ConjugateGradient
A conjugate gradient solver for sparse self-adjoint problems.
class CwiseBinaryOp
Generic expression where a coefficient-wise binary operator is applied to two expressions.
class CwiseNullaryOp
Generic expression of a matrix where all coefficients are defined by a functor.
class CwiseUnaryOp
Generic expression where a coefficient-wise unary operator is applied to an expression.
class CwiseUnaryView
Generic lvalue expression of a coefficient-wise unary operator of a matrix or a vector.
struct Dense
class DenseBase
Base class for all dense matrices, vectors, and arrays.
class DenseCoeffsBase< Derived, DirectAccessors >
Base class providing direct read-only coefficient access to matrices and arrays.
class DenseCoeffsBase< Derived, DirectWriteAccessors >
Base class providing direct read/write coefficient access to matrices and arrays.
class DenseCoeffsBase< Derived, ReadOnlyAccessors >
Base class providing read-only coefficient access to matrices and arrays.
class DenseCoeffsBase< Derived, WriteAccessors >
Base class providing read/write coefficient access to matrices and arrays.
class Diagonal
Expression of a diagonal/subdiagonal/superdiagonal in a matrix.
class DiagonalMatrix
Represents a diagonal matrix with its storage.
class DiagonalPreconditioner
A preconditioner based on the digonal entries.
class DiagonalWrapper
Expression of a diagonal matrix.
struct EigenBase
class EigenSolver
Computes eigenvalues and eigenvectors of general matrices.
class ForceAlignedAccess
Enforce aligned packet loads and stores regardless of what is requested.
class FullPivHouseholderQR
Householder rank-revealing QR decomposition of a matrix with full pivoting.
class FullPivLU
LU decomposition of a matrix with complete pivoting, and related features.
class GeneralizedEigenSolver
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
class GeneralizedSelfAdjointEigenSolver
Computes eigenvalues and eigenvectors of the generalized selfadjoint eigen problem.
class GeneralProduct
Expression of the product of two general matrices or vectors.
class HessenbergDecomposition
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
class Homogeneous
Expression of one (or a set of) homogeneous vector(s)
class HouseholderQR
Householder QR decomposition of a matrix.
class HouseholderSequence
Sequence of Householder reflections acting on subspaces with decreasing size.
class Hyperplane
A hyperplane.
class IdentityPreconditioner
A naive preconditioner which approximates any matrix as the identity matrix.
class IncompleteLUT
Incomplete LU factorization with dual-threshold strategy.
class InnerStride
Convenience specialization of Stride to specify only an inner stride See class Map for some examples.
class IOFormat
Stores a set of parameters controlling the way matrices are printed.
class IterativeSolverBase
Base class for linear iterative solvers.
class JacobiRotation
Rotation given by a cosine-sine pair.
class JacobiSVD
Two-sided Jacobi SVD decomposition of a rectangular matrix.
class LDLT
Robust Cholesky decomposition of a matrix with pivoting.
class LLT
Standard Cholesky decomposition (LL^T) of a matrix and associated features.
class Map
A matrix or vector expression mapping an existing array of data.
class Map< const Quaternion< _Scalar >, _Options >
Quaternion expression mapping a constant memory buffer.
class Map< Quaternion< _Scalar >, _Options >
Expression of a quaternion from a memory buffer.
class MapBase
Base class for Map and Block expression with direct access.
class MappedSparseMatrix
Sparse matrix.
class Matrix
The matrix class, also used for vectors and row-vectors.
class MatrixBase
Base class for all dense matrices, vectors, and expressions.
class MatrixWrapper
Expression of an array as a mathematical vector or matrix.
struct MatrixXpr
class MetisOrdering
class NaturalOrdering
class NestByValue
Expression which must be nested by value.
class NoAlias
Pseudo expression providing an operator = assuming no aliasing.
class NumTraits
Holds information about the various numeric (i.e. scalar) types allowed by Eigen.
class OuterStride
Convenience specialization of Stride to specify only an outer stride See class Map for some examples.
class ParametrizedLine
A parametrized line.
class PardisoLDLT
A sparse direct Cholesky (LDLT) factorization and solver based on the PARDISO library.
class PardisoLLT
A sparse direct Cholesky (LLT) factorization and solver based on the PARDISO library.
class PardisoLU
A sparse direct LU factorization and solver based on the PARDISO library.
class PartialPivLU
LU decomposition of a matrix with partial pivoting, and related features.
class PartialReduxExpr
Generic expression of a partially reduxed matrix.
class PastixLDLT
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
class PastixLLT
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
class PastixLU
Interface to the PaStix solver.
class PermutationBase
Base class for permutations.
class PermutationMatrix
Permutation matrix.
class PermutationWrapper
Class to view a vector of integers as a permutation matrix.
class PlainObjectBase
Dense storage base class for matrices and arrays.
class ProductReturnType
Helper class to get the correct and optimized returned type of operator*.
class Quaternion
The quaternion class used to represent 3D orientations and rotations.
class QuaternionBase
Base class for quaternion expressions.
class RealQZ
Performs a real QZ decomposition of a pair of square matrices.
class RealSchur
Performs a real Schur decomposition of a square matrix.
class Ref
A matrix or vector expression mapping an existing expressions.
class Replicate
Expression of the multiple replication of a matrix or vector.
class Reverse
Expression of the reverse of a vector or matrix.
class Rotation2D
Represents a rotation/orientation in a 2 dimensional space.
class RotationBase
Common base class for compact rotation representations.
class Select
Expression of a coefficient wise version of the C++ ternary operator ?:
class SelfAdjointEigenSolver
Computes eigenvalues and eigenvectors of selfadjoint matrices.
class SelfAdjointView
Expression of a selfadjoint matrix from a triangular part of a dense matrix.
class SimplicialCholesky
class SimplicialCholeskyBase
A direct sparse Cholesky factorizations.
class SimplicialLDLT
A direct sparse LDLT Cholesky factorizations without square root.
class SimplicialLLT
A direct sparse LLT Cholesky factorizations.
struct Sparse
class SparseLU
Sparse supernodal LU factorization for general matrices.
class SparseMatrix
A versatible sparse matrix representation.
class SparseMatrixBase
Base class of any sparse matrices or sparse expressions.
class SparseQR
Sparse left-looking rank-revealing QR factorization.
class SparseSelfAdjointView
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
class SparseVector
a sparse vector class
class SPQR
Sparse QR factorization based on SuiteSparseQR library.
class Stride
Holds strides information for Map.
class SuperILU
A sparse direct incomplete LU factorization and solver based on the SuperLU library.
class SuperLU
A sparse direct LU factorization and solver based on the SuperLU library.
class SuperLUBase
The base class for the direct and incomplete LU factorization of SuperLU.
class Transform
Represents an homogeneous transformation in a N dimensional space.
class Translation
Represents a translation transformation.
class Transpose
Expression of the transpose of a matrix.
class Transpositions
Represents a sequence of transpositions (row/column interchange)
class TriangularView
Base class for triangular part in a matrix.
class Tridiagonalization
Tridiagonal decomposition of a selfadjoint matrix.
class Triplet
A small structure to hold a non zero as a triplet (i,j,value).
class UmfPackLU
A sparse LU factorization and solver based on UmfPack.
class VectorBlock
Expression of a fixed-size or dynamic-size sub-vector.
class VectorwiseOp
Pseudo expression providing partial reduction operations.
class WithFormat
Pseudo expression providing matrix output with given format.
Typedefs
typedef Transform< double,
2, Affine > Affine2d
typedef Transform< float,
2, Affine > Affine2f
typedef Transform< double,
3, Affine > Affine3d
typedef Transform< float,
3, Affine > Affine3f
typedef Transform< double,
2, AffineCompact > AffineCompact2d
typedef Transform< float,
2, AffineCompact > AffineCompact2f
typedef Transform< double,
3, AffineCompact > AffineCompact3d
typedef Transform< float,
3, AffineCompact > AffineCompact3f
typedef AlignedBox< double, 1 > AlignedBox1d
typedef AlignedBox< float, 1 > AlignedBox1f
typedef AlignedBox< int, 1 > AlignedBox1i
typedef AlignedBox< double, 2 > AlignedBox2d
typedef AlignedBox< float, 2 > AlignedBox2f
typedef AlignedBox< int, 2 > AlignedBox2i
typedef AlignedBox< double, 3 > AlignedBox3d
typedef AlignedBox< float, 3 > AlignedBox3f
typedef AlignedBox< int, 3 > AlignedBox3i
typedef AlignedBox< double, 4 > AlignedBox4d
typedef AlignedBox< float, 4 > AlignedBox4f
typedef AlignedBox< int, 4 > AlignedBox4i
typedef AlignedBox< double,
Dynamic > AlignedBoxXd
typedef AlignedBox< float,
Dynamic > AlignedBoxXf
typedef AlignedBox< int, Dynamic > AlignedBoxXi
typedef DiagonalMatrix< double, 2 > AlignedScaling2d
typedef DiagonalMatrix< float, 2 > AlignedScaling2f
typedef DiagonalMatrix< double, 3 > AlignedScaling3d
typedef DiagonalMatrix< float, 3 > AlignedScaling3f
typedef AngleAxis< double > AngleAxisd
typedef AngleAxis< float > AngleAxisf
typedef Transform< double,
2, Isometry > Isometry2d
typedef Transform< float,
2, Isometry > Isometry2f
typedef Transform< double,
3, Isometry > Isometry3d
typedef Transform< float,
3, Isometry > Isometry3f
typedef Matrix< std::complex
< double >, 2, 2 > Matrix2cd
typedef Matrix< std::complex
< float >, 2, 2 > Matrix2cf
typedef Matrix< double, 2, 2 > Matrix2d
typedef Matrix< float, 2, 2 > Matrix2f
typedef Matrix< int, 2, 2 > Matrix2i
typedef Matrix< std::complex
< double >, 2, Dynamic > Matrix2Xcd
typedef Matrix< std::complex
< float >, 2, Dynamic > Matrix2Xcf
typedef Matrix< double,
2, Dynamic > Matrix2Xd
typedef Matrix< float, 2, Dynamic > Matrix2Xf
typedef Matrix< int, 2, Dynamic > Matrix2Xi
typedef Matrix< std::complex
< double >, 3, 3 > Matrix3cd
typedef Matrix< std::complex
< float >, 3, 3 > Matrix3cf
typedef Matrix< double, 3, 3 > Matrix3d
typedef Matrix< float, 3, 3 > Matrix3f
typedef Matrix< int, 3, 3 > Matrix3i
typedef Matrix< std::complex
< double >, 3, Dynamic > Matrix3Xcd
typedef Matrix< std::complex
< float >, 3, Dynamic > Matrix3Xcf
typedef Matrix< double,
3, Dynamic > Matrix3Xd
typedef Matrix< float, 3, Dynamic > Matrix3Xf
typedef Matrix< int, 3, Dynamic > Matrix3Xi
typedef Matrix< std::complex
< double >, 4, 4 > Matrix4cd
typedef Matrix< std::complex
< float >, 4, 4 > Matrix4cf
typedef Matrix< double, 4, 4 > Matrix4d
typedef Matrix< float, 4, 4 > Matrix4f
typedef Matrix< int, 4, 4 > Matrix4i
typedef Matrix< std::complex
< double >, 4, Dynamic > Matrix4Xcd
typedef Matrix< std::complex
< float >, 4, Dynamic > Matrix4Xcf
typedef Matrix< double,
4, Dynamic > Matrix4Xd
typedef Matrix< float, 4, Dynamic > Matrix4Xf
typedef Matrix< int, 4, Dynamic > Matrix4Xi
typedef Matrix< std::complex
< double >, Dynamic, 2 > MatrixX2cd
typedef Matrix< std::complex
< float >, Dynamic, 2 > MatrixX2cf
typedef Matrix< double,
Dynamic, 2 > MatrixX2d
typedef Matrix< float, Dynamic, 2 > MatrixX2f
typedef Matrix< int, Dynamic, 2 > MatrixX2i
typedef Matrix< std::complex
< double >, Dynamic, 3 > MatrixX3cd
typedef Matrix< std::complex
< float >, Dynamic, 3 > MatrixX3cf
typedef Matrix< double,
Dynamic, 3 > MatrixX3d
typedef Matrix< float, Dynamic, 3 > MatrixX3f
typedef Matrix< int, Dynamic, 3 > MatrixX3i
typedef Matrix< std::complex
< double >, Dynamic, 4 > MatrixX4cd
typedef Matrix< std::complex
< float >, Dynamic, 4 > MatrixX4cf
typedef Matrix< double,
Dynamic, 4 > MatrixX4d
typedef Matrix< float, Dynamic, 4 > MatrixX4f
typedef Matrix< int, Dynamic, 4 > MatrixX4i
typedef Matrix< std::complex
< double >, Dynamic, Dynamic > MatrixXcd
typedef Matrix< std::complex
< float >, Dynamic, Dynamic > MatrixXcf
typedef Matrix< double,
Dynamic, Dynamic > MatrixXd
typedef Matrix< float, Dynamic,
Dynamic > MatrixXf
typedef Matrix< int, Dynamic,
Dynamic > MatrixXi
typedef Transform< double,
2, Projective > Projective2d
typedef Transform< float,
2, Projective > Projective2f
typedef Transform< double,
3, Projective > Projective3d
typedef Transform< float,
3, Projective > Projective3f
typedef Quaternion< double > Quaterniond
typedef Quaternion< float > Quaternionf
typedef Map< Quaternion
< double >, Aligned > QuaternionMapAlignedd
typedef Map< Quaternion< float >
, Aligned > QuaternionMapAlignedf
typedef Map< Quaternion
< double >, 0 > QuaternionMapd
typedef Map< Quaternion< float >, 0 > QuaternionMapf
typedef Rotation2D< double > Rotation2Dd
typedef Rotation2D< float > Rotation2Df
typedef Matrix< std::complex
< double >, 1, 2 > RowVector2cd
typedef Matrix< std::complex
< float >, 1, 2 > RowVector2cf
typedef Matrix< double, 1, 2 > RowVector2d
typedef Matrix< float, 1, 2 > RowVector2f
typedef Matrix< int, 1, 2 > RowVector2i
typedef Matrix< std::complex
< double >, 1, 3 > RowVector3cd
typedef Matrix< std::complex
< float >, 1, 3 > RowVector3cf
typedef Matrix< double, 1, 3 > RowVector3d
typedef Matrix< float, 1, 3 > RowVector3f
typedef Matrix< int, 1, 3 > RowVector3i
typedef Matrix< std::complex
< double >, 1, 4 > RowVector4cd
typedef Matrix< std::complex
< float >, 1, 4 > RowVector4cf
typedef Matrix< double, 1, 4 > RowVector4d
typedef Matrix< float, 1, 4 > RowVector4f
typedef Matrix< int, 1, 4 > RowVector4i
typedef Matrix< std::complex
< double >, 1, Dynamic > RowVectorXcd
typedef Matrix< std::complex
< float >, 1, Dynamic > RowVectorXcf
typedef Matrix< double,
1, Dynamic > RowVectorXd
typedef Matrix< float, 1, Dynamic > RowVectorXf
typedef Matrix< int, 1, Dynamic > RowVectorXi
typedef Matrix< std::complex
< double >, 2, 1 > Vector2cd
typedef Matrix< std::complex
< float >, 2, 1 > Vector2cf
typedef Matrix< double, 2, 1 > Vector2d
typedef Matrix< float, 2, 1 > Vector2f
typedef Matrix< int, 2, 1 > Vector2i
typedef Matrix< std::complex
< double >, 3, 1 > Vector3cd
typedef Matrix< std::complex
< float >, 3, 1 > Vector3cf
typedef Matrix< double, 3, 1 > Vector3d
typedef Matrix< float, 3, 1 > Vector3f
typedef Matrix< int, 3, 1 > Vector3i
typedef Matrix< std::complex
< double >, 4, 1 > Vector4cd
typedef Matrix< std::complex
< float >, 4, 1 > Vector4cf
typedef Matrix< double, 4, 1 > Vector4d
typedef Matrix< float, 4, 1 > Vector4f
typedef Matrix< int, 4, 1 > Vector4i
typedef Matrix< std::complex
< double >, Dynamic, 1 > VectorXcd
typedef Matrix< std::complex
< float >, Dynamic, 1 > VectorXcf
typedef Matrix< double,
Dynamic, 1 > VectorXd
typedef Matrix< float, Dynamic, 1 > VectorXf
typedef Matrix< int, Dynamic, 1 > VectorXi
Enumerations
enum {
Lower,
Upper,
UnitDiag,
ZeroDiag,
UnitLower,
UnitUpper,
StrictlyLower,
StrictlyUpper,
SelfAdjoint,
Symmetric
}
enum {
Unaligned,
Aligned
}
enum {
ColMajor,
RowMajor,
AutoAlign,
DontAlign
}
enum {
OnTheLeft,
OnTheRight
}
enum AccessorLevels {
ReadOnlyAccessors,
WriteAccessors,
DirectAccessors,
DirectWriteAccessors
}
enum ComputationInfo {
Success,
NumericalIssue,
NoConvergence,
InvalidInput
}
enum CornerType
enum DecompositionOptions { ,
ComputeFullU,
ComputeThinU,
ComputeFullV,
ComputeThinV,
EigenvaluesOnly,
ComputeEigenvectors ,
Ax_lBx,
ABx_lx,
BAx_lx
}
enum DirectionType {
Vertical,
Horizontal,
BothDirections
}
enum QRPreconditioners {
NoQRPreconditioner,
HouseholderQRPreconditioner,
ColPivHouseholderQRPreconditioner,
FullPivHouseholderQRPreconditioner
}
enum TransformTraits {
Isometry,
Affine,
AffineCompact,
Projective
}
Functions
template<typename VectorsType , typename CoeffsType >
HouseholderSequence
< VectorsType, CoeffsType > householderSequence (const VectorsType &v, const CoeffsType &h)
Convenience function for constructing a Householder sequence.
void initParallel ()
std::ptrdiff_t l1CacheSize ()
std::ptrdiff_t l2CacheSize ()
int nbThreads ()
template<typename SparseDerived , typename PermDerived >
const
internal::permut_sparsematrix_product_retval
< PermutationBase< PermDerived >
, SparseDerived, OnTheRight,
false > operator* (const SparseMatrixBase< SparseDerived > &matrix, const PermutationBase< PermDerived > &perm)
template<typename SparseDerived , typename PermDerived >
const
internal::permut_sparsematrix_product_retval
< PermutationBase< PermDerived >
, SparseDerived, OnTheLeft,
false > operator* (const PermutationBase< PermDerived > &perm, const SparseMatrixBase< SparseDerived > &matrix)
template<typename SparseDerived , typename PermDerived >
const
internal::permut_sparsematrix_product_retval
< PermutationBase< PermDerived >
, SparseDerived, OnTheRight,
true > operator* (const SparseMatrixBase< SparseDerived > &matrix, const Transpose< PermutationBase< PermDerived > > &tperm)
template<typename SparseDerived , typename PermDerived >
const
internal::permut_sparsematrix_product_retval
< PermutationBase< PermDerived >
, SparseDerived, OnTheLeft,
true > operator* (const Transpose< PermutationBase< PermDerived > > &tperm, const SparseMatrixBase< SparseDerived > &matrix)
template<typename Derived , typename TranspositionsDerived >
const
internal::transposition_matrix_product_retval
< TranspositionsDerived,
Derived, OnTheRight > operator* (const MatrixBase< Derived > &matrix, const TranspositionsBase< TranspositionsDerived > &transpositions)
template<typename Derived , typename TranspositionDerived >
const
internal::transposition_matrix_product_retval
< TranspositionDerived,
Derived, OnTheLeft > operator* (const TranspositionsBase< TranspositionDerived > &transpositions, const MatrixBase< Derived > &matrix)
template<typename OtherDerived , typename VectorsType , typename CoeffsType , int Side>
internal::matrix_type_times_scalar_type
< typename VectorsType::Scalar,
OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other, const HouseholderSequence< VectorsType, CoeffsType, Side > &h)
Computes the product of a matrix with a Householder sequence.
template<typename Derived , typename PermutationDerived >
const
internal::permut_matrix_product_retval
< PermutationDerived, Derived,
OnTheRight > operator* (const MatrixBase< Derived > &matrix, const PermutationBase< PermutationDerived > &permutation)
template<typename Derived , typename PermutationDerived >
const
internal::permut_matrix_product_retval
< PermutationDerived, Derived,
OnTheLeft > operator* (const PermutationBase< PermutationDerived > &permutation, const MatrixBase< Derived > &matrix)
template<typename Derived >
const Eigen::CwiseUnaryOp
< Eigen::internal::scalar_inverse_mult_op
< typename Derived::Scalar >
, const Derived > operator/ (const typename Derived::Scalar &s, const Eigen::ArrayBase< Derived > &a)
Component-wise division of a scalar by array elements.
template<typename VectorsType , typename CoeffsType >
HouseholderSequence
< VectorsType, CoeffsType,
OnTheRight > rightHouseholderSequence (const VectorsType &v, const CoeffsType &h)
Convenience function for constructing a Householder sequence.
void setCpuCacheSizes (std::ptrdiff_t l1, std::ptrdiff_t l2)
void setNbThreads (int v)
template<typename Derived , typename OtherDerived >
internal::umeyama_transform_matrix_type
< Derived, OtherDerived >
::type umeyama (const MatrixBase< Derived > &src, const MatrixBase< OtherDerived > &dst, bool with_scaling=true)
Returns the transformation between two point sets.
template<typename _Scalar , int _Options, typename _Index >
cholmod_sparse viewAsCholmod (SparseMatrix< _Scalar, _Options, _Index > &mat)
template<typename _Scalar , int _Options, typename _Index , unsigned int UpLo>
cholmod_sparse viewAsCholmod (const SparseSelfAdjointView< SparseMatrix< _Scalar, _Options, _Index >, UpLo > &mat)
template<typename Derived >
cholmod_dense viewAsCholmod (MatrixBase< Derived > &mat)
template<typename Scalar , int Flags, typename Index >
MappedSparseMatrix< Scalar,
Flags, Index > viewAsEigen (cholmod_sparse &cm)
Variables
const unsigned int ActualPacketAccessBit
const unsigned int AlignedBit
const unsigned int DirectAccessBit
const int Dynamic
const int DynamicIndex
const unsigned int EvalBeforeAssigningBit
const unsigned int EvalBeforeNestingBit
const int Infinity
const unsigned int LinearAccessBit
const unsigned int LvalueBit
const unsigned int PacketAccessBit
const unsigned int RowMajorBit
Detailed Description
Namespace containing all symbols from the Eigen library.
Function Documentation
void Eigen::initParallel () inline
Must be call first when calling Eigen from multiple threads
std::ptrdiff_t Eigen::l1CacheSize () inline
Returns
the currently set level 1 cpu cache size (in bytes) used to estimate the ideal blocking size parameters.
See Also
setCpuCacheSize
std::ptrdiff_t Eigen::l2CacheSize () inline
Returns
the currently set level 2 cpu cache size (in bytes) used to estimate the ideal blocking size parameters.
See Also
setCpuCacheSize
int Eigen::nbThreads () inline
Returns
the max number of threads reserved for Eigen
See Also
setNbThreads
const internal::permut_sparsematrix_product_retval<PermutationBase<PermDerived>, SparseDerived, OnTheRight, false> Eigen::operator* (const SparseMatrixBase< SparseDerived > & matrix, const PermutationBase< PermDerived > & perm) inline
Returns
the matrix with the permutation applied to the columns
References EigenBase< Derived >::derived(), and OnTheRight.
const internal::permut_sparsematrix_product_retval<PermutationBase<PermDerived>, SparseDerived, OnTheLeft, false> Eigen::operator* (const PermutationBase< PermDerived > & perm, const SparseMatrixBase< SparseDerived > & matrix) inline
Returns
the matrix with the permutation applied to the rows
References EigenBase< Derived >::derived(), and OnTheLeft.
const internal::permut_sparsematrix_product_retval<PermutationBase<PermDerived>, SparseDerived, OnTheRight, true> Eigen::operator* (const SparseMatrixBase< SparseDerived > & matrix, const Transpose< PermutationBase< PermDerived > > & tperm) inline
Returns
the matrix with the inverse permutation applied to the columns.
References EigenBase< Derived >::derived(), and OnTheRight.
const internal::permut_sparsematrix_product_retval<PermutationBase<PermDerived>, SparseDerived, OnTheLeft, true> Eigen::operator* (const Transpose< PermutationBase< PermDerived > > & tperm, const SparseMatrixBase< SparseDerived > & matrix) inline
Returns
the matrix with the inverse permutation applied to the rows.
References EigenBase< Derived >::derived(), and OnTheLeft.
const internal::transposition_matrix_product_retval<TranspositionsDerived, Derived, OnTheRight> Eigen::operator* (const MatrixBase< Derived > & matrix, const TranspositionsBase< TranspositionsDerived > & transpositions) inline
Returns
the matrix with the transpositions applied to the columns.
References OnTheRight.
const internal::transposition_matrix_product_retval<TranspositionDerived, Derived, OnTheLeft> Eigen::operator* (const TranspositionsBase< TranspositionDerived > & transpositions, const MatrixBase< Derived > & matrix) inline
Returns
the matrix with the transpositions applied to the rows.
References OnTheLeft.
internal::matrix_type_times_scalar_type<typename VectorsType::Scalar,OtherDerived>::Type Eigen::operator* (const MatrixBase< OtherDerived > & other, const HouseholderSequence< VectorsType, CoeffsType, Side > & h)
Computes the product of a matrix with a Householder sequence.
Parameters
[in] other Matrix being multiplied.
[in] h HouseholderSequence being multiplied.
Returns
Expression object representing the product.
This function computes where is the matrix other and is the Householder sequence represented by h.
const internal::permut_matrix_product_retval<PermutationDerived, Derived, OnTheRight> Eigen::operator* (const MatrixBase< Derived > & matrix, const PermutationBase< PermutationDerived > & permutation) inline
Returns
the matrix with the permutation applied to the columns.
References EigenBase< Derived >::derived(), and OnTheRight.
const internal::permut_matrix_product_retval<PermutationDerived, Derived, OnTheLeft> Eigen::operator* (const PermutationBase< PermutationDerived > & permutation, const MatrixBase< Derived > & matrix) inline
Returns
the matrix with the permutation applied to the rows.
References EigenBase< Derived >::derived(), and OnTheLeft.
void Eigen::setCpuCacheSizes (std::ptrdiff_t l1, std::ptrdiff_t l2) inline
Set the cpu L1 and L2 cache sizes (in bytes). These values are use to adjust the size of the blocks for the algorithms working per blocks.
See Also
computeProductBlockingSizes
void Eigen::setNbThreads (int v) inline
Sets the max number of threads reserved for Eigen
See Also
nbThreads
cholmod_sparse Eigen::viewAsCholmod (SparseMatrix< _Scalar, _Options, _Index > & mat)
Wraps the Eigen sparse matrix mat into a Cholmod sparse matrix object. Note that the data are shared.
References SparseMatrix< _Scalar, _Options, _Index >::cols(), SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), SparseMatrix< _Scalar, _Options, _Index >::innerNonZeroPtr(), SparseMatrix< _Scalar, _Options, _Index >::isCompressed(), SparseMatrix< _Scalar, _Options, _Index >::nonZeros(), SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), SparseMatrix< _Scalar, _Options, _Index >::rows(), and SparseMatrix< _Scalar, _Options, _Index >::valuePtr().
Referenced by CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::analyzePattern(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::factorize(), and viewAsCholmod().
cholmod_sparse Eigen::viewAsCholmod (const SparseSelfAdjointView< SparseMatrix< _Scalar, _Options, _Index >, UpLo > & mat)
Returns a view of the Eigen sparse matrix mat as Cholmod sparse matrix. The data are not copied but shared.
References Lower, Upper, and viewAsCholmod().
cholmod_dense Eigen::viewAsCholmod (MatrixBase< Derived > & mat)
Returns a view of the Eigen dense matrix mat as Cholmod dense matrix. The data are not copied but shared.
References RowMajorBit.
MappedSparseMatrix<Scalar,Flags,Index> Eigen::viewAsEigen (cholmod_sparse & cm)
Returns a view of the Cholmod sparse matrix cm as an Eigen sparse matrix. The data are not copied but shared.
Variable Documentation
const int Dynamic
This value means that a positive quantity (e.g., a size) is not known at compile-time, and that instead the value is stored in some runtime variable.
Changing the value of Dynamic breaks the ABI, as Dynamic is often used as a template parameter for Matrix.
Referenced by AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), DenseBase< Derived >::all(), DenseBase< Derived >::any(), Array< Index, 64, 1, DontAlign >::Array(), Block< XprType, BlockRows, BlockCols, InnerPanel >::Block(), AlignedBox< _Scalar, _AmbientDim >::dim(), Hyperplane< _Scalar, _AmbientDim, Options >::dim(), MatrixBase< Derived >::lazyProduct(), Matrix< Scalar, Index(AmbientDimAtCompileTime)==Dynamic?Dynamic:Index(AmbientDimAtCompileTime)+1, 1, Options >::Matrix(), MatrixBase< Derived >::operator*(), DenseBase< Derived >::prod(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Stride< 0, Value >::Stride(), DenseBase< Derived >::sum(), DenseBase< Derived >::transposeInPlace(), and DenseBase< Derived >::visit().
const int DynamicIndex
This value means that a signed quantity (e.g., a signed index) is not known at compile-time, and that instead its value has to be specified at runtime.
const int Infinity
This value means +Infinity; it is currently used only as the p parameter to MatrixBase::lpNorm<int>(). The value Infinity there means the L-infinity norm.